### ISSUE TITLE
Feature: Feature: menu/other UI from header avatar with username

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#105]
### Type of feature

🍕 Feature

### Current behavior

When you login to the app the GitHub profile avatar appears in the top right-hand corner. The avatar doubles as a logout button and that are not clear to the user who may be trying to click through a profile..

### Suggested solution

It would be ideal to make the profile a dropdown so the user can get details of the app. This was done in [opensauzed.pizza](https://opensauced.pizza/) by @blackgirlbytes https://github.com/open-sauced/open-sauced/pull/1129/files

<img width="214" alt="Screen Shot 2022-01-23 at 7 53 31 PM" src="https://user-images.githubusercontent.com/5713670/150719821-6770ca6c-5f3b-4f04-befc-6fd114af5755.png">

### Additional context

Please use Taildwind to accomplish this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nulfrost** [comment]
.take

**Comment by nulfrost** [comment]
Would it be okay to utilize https://headlessui.dev/react/menu ? These components come with accessibility features out of the box and can still be styled with tailwind further if needed

**Comment by 0-vortex** [comment]
> Would it be okay to utilize https://headlessui.dev/react/menu ? These components come with accessibility features out of the box and can still be styled with tailwind further if needed

Don't see any problem with that approach! 🍕 🚀
