### ISSUE TITLE
Feature: Include version number in the console. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#106]
### Type of feature

🍕 Feature

### Current behavior

This app relies on semantic versioning and it would be ideal to let the user know what version they are using. 

### Suggested solution

In the flagship app we highlight the version in the console. 
<img width="1440" alt="Screen Shot 2022-01-23 at 8 00 09 PM" src="https://user-images.githubusercontent.com/5713670/150720051-b2103d7b-ea0d-4791-ae8f-5cf278634bd8.png">

1. Include [fetch version lib](https://github.com/open-sauced/open-sauced/blob/main/src/lib/appVersion.js) similar to open sauced.
2. [Add ascii art](https://github.com/open-sauced/open-sauced/blob/eb1bb9030cbc0bba6d883d5ed933e99f5488ea14/src/index.jsx#L43-L49) to the index page. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
This sounds like a job for me :D `.take`

**Comment by 0-vortex** [comment]
Currently, we are building the static build output in https://github.com/open-sauced/hot/blob/0e9b53137bb252e1c6c2ffca9ed9502cd552c399/.github/workflows/release.yml#L62 and Netlify build is picking up deployment before the release action finishes.

After some thorough investigation, both should be fixed for this issue to be successfully closed. The PR for this might come in 2 parts! 🍕

**Comment by 0-vortex** [comment]
This might be permanently broken in the docker build, have to investigate if using the same plugin is possible

**Comment by 0-vortex** [comment]
We can get the version out of `package.json` with Vite, like we do in the `PrimaryNav` - un-assigning and adding this like a GFI, what do you think @bdougie ?

**Comment by bdougie** [comment]
@CMCSWEENE this is the code I would put at the top of the App.tsx [here](https://github.com/open-sauced/hot/blob/beta/src/App.tsx#L12).

```
import { version } from "../../package.json";

    console.log(`%c
 ██████╗ ██████╗ ███████╗███╗   ██╗    ███████╗ █████╗ ██╗   ██╗ ██████╗███████╗██████╗
██╔═══██╗██╔══██╗██╔════╝████╗  ██║    ██╔════╝██╔══██╗██║   ██║██╔════╝██╔════╝██╔══██╗
██║   ██║██████╔╝█████╗  ██╔██╗ ██║    ███████╗███████║██║   ██║██║     █████╗  ██║  ██║
██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║    ╚════██║██╔══██║██║   ██║██║     ██╔══╝  ██║  ██║
╚██████╔╝██║     ███████╗██║ ╚████║    ███████║██║  ██║╚██████╔╝╚██████╗███████╗██████╔╝
 ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝╚══════╝╚═════╝%c v${version()}`,
    "color:#f6d82b",
    "color:green;font-weight:bold");
```

**Comment by erinmikailstaples** [comment]
.take

**Comment by erinmikailstaples** [comment]
**Workflow**

Set up: 
- Forked repo, [cloned it here.](https://github.com/erinmikailstaples/hot-add-version-number-console)

**Task 1: Include [fetch version lib](https://github.com/open-sauced/open-sauced/blob/main/src/lib/appVersion.js) similar to open sauced.**

- Added new file under lib > `appVersion.js` and copied over the version page 

![Image](https://user-images.githubusercontent.com/54031531/186278874-7fb62bf0-095e-4eca-83b4-f7b267c01c3d.png)

**Task 2: [Add ascii art](https://github.com/open-sauced/open-sauced/blob/eb1bb9030cbc0bba6d883d5ed933e99f5488ea14/src/index.jsx#L43-L49) to the index page.**

- Added ascii art to the index page here: 

![Image](https://user-images.githubusercontent.com/54031531/186279117-4b7a76f8-6311-4d14-9d49-b36502a572f9.png)


- Add ascii art [here as well](https://github.com/open-sauced/hot/issues/106#issuecomment-1217018904)

1. Opened src > app.tsx + added the ascii art starting on line 13 (view below)

![Image](https://user-images.githubusercontent.com/54031531/186277445-e76d8500-98e1-49df-b7d8-c2556ab74c89.png)

Syncing to the [repo here](https://github.com/erinmikailstaples/hot-add-version-number-console) now.
