### ISSUE TITLE
Bug: login return URL does not work with local development

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#108]
### Describe the bug

Need `.env` populated with local development database and have its Auth set up for `localhost:3000` redirect.

### Steps to reproduce

1. start local development
2. login
3. get redirected to https://hot.opensauced.pizza

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
@bdougie think this one is for you :D

**Comment by bdougie** [comment]
Looking to fix this now. The solution I got is this:

```js
  return {
    signIn: (data) => supabase.auth.signIn(data, {
      redirectTo: 'http://localhost:3000/'
    }),
    signOut: () => supabase.auth.signOut(),
    user,
  };
```

From what I read, having a separate localhost auth is the preferred solution. https://github.com/supabase/supabase/discussions/600
