### ISSUE TITLE
Feature: Create a Stafftool bar when user is logged in

### ISSUE THREAD

**Issue by blackgirlbytes** [open-sauced/hot#110]
### Type of feature

🍕 Feature

### Current behavior

Currently, when you log in, there is not staff tool bar.

### Suggested solution

Been chatting with Brian, and some applications have this feature for projects ..when you press the ` on your keyboard it should toggle a black bar that gives details about the version number, the branch, and admin access (if that's a thing in this project).

I spoke with Brian about working on this, if that's okay ❤️ 

### Additional context

Questioning if the staff tool bar should be available to everyone or only admins. Do admins exist in this project?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
CS 1.6 🔫 🍕 - once toggled, will it support some simple commands like "help"? :D

**Comment by blackgirlbytes** [comment]
That's a great idea @0-vortex ! I'm open to ideas. I only have the GitHub staffbar as my example, but maybe some of the items on it ..aren't as relevant to this project

**Comment by 0-vortex** [comment]
> That's a great idea @0-vortex ! I'm open to ideas. I only have the GitHub staffbar as my example, but maybe some of the items on it ..aren't as relevant to this project

I don't know the GitHub bar, was just thinking of Counter-Strike 🤣 

![](https://www.tobyscs.com/files/cs-how-to-activate-console.jpg)

**Comment by blackgirlbytes** [comment]
ohhhh my b..that's what CS 1.6  is <-- had no clue.

**Comment by bdougie** [comment]
The staff bar exist in the app.opensauced.pizza 

https://github.com/open-sauced/open-sauced/blob/main/src/components/AdminStatsBar.jsx

The first step should be listing the user count in a bar that only appears to members of the organization.
