### ISSUE TITLE
Feature: Link to user profile in the user dropdown.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#111]
### Type of feature

🍕 Feature

### Current behavior

![Screen Shot 2022-01-26 at 7 22 55 AM](https://user-images.githubusercontent.com/5713670/151192045-7ad033d0-5347-46a1-a44f-5f119e616014.png)

When logged in the user name is shown. That should be a hyperlink to their github profile (i.e. github.com/bdougie)

### Suggested solution

This line https://github.com/open-sauced/hot/blob/main/src/components/PrimaryNav.jsx#L40

Should be wrapped with an anchor tag and dynamic hyperlink 

```
<a href={`https://github.com/${user.user_metadata.user_name}`}>............</a>
```

### Additional context

Localhost will not allow you to log in, so you will not be able to test this. #108 will fix this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajat4984** [comment]
Hey i think i can resolve this issue can you assign this to me

**Comment by 0-vortex** [comment]
> Hey i think i can resolve this issue can you assign this to me

Make sure to check out the [contributing guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues)!

**Comment by rajat4984** [comment]
.take
