### ISSUE TITLE
Feature: Implement voting logic for repos

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#12]
### Type of feature

Feature

### Current behavior

Today the api is listing repos based on relevancy in open sauced. 

- api.opensauced.pizza
- The above is powered by a private DB hosted on [supabase](https://supabase.com/)

### Desired solution

We need a global state that can store votes from users

- Add local state to fetch vote data
- Implement vote column in supabase db
- Alternatively we could use a public JSON file to store votes as an intermediary.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
IMHO anything calling a specific microservice or API endpoint could use some local mocking or container composing. How do you feel about doing some compatibility upgrades in https://github.com/open-sauced/hot-sauce-api ?

**Comment by bdougie** [comment]
Hey, @0-vortex interested in hearing more about this microservice. I think I will try to figure out the voting logic this week. I am thinking about creating a table in the supabase DB with votes captured. I am also thinking this will be blocked slightly by #20, since I will need to store the votes based on the logged-in user. 

Also, side note: I am going to look into making the data public via the new [supabase studio](https://supabase.com/blog/2021/11/30/supabase-studio).

**Comment by bdougie** [comment]
Going to be starting work on this. The current plan

- [ ] Create table stores votes that stores votes from users: githubUserIds, and vote timestamps
- [ ] Write votes to the recommendations table
- [ ] Mock GitHub login until #20 
- [ ] Connect supabase client to write to DB directly
- [ ] Implement local state storage.
- [ ] Implement API automation for updates.

**Comment by hokagedemehin** [comment]
You can also consider using React Context API for global state management. That way you can have a save a vote and have it available across the app for other components to use. 

Redux can also do the same but I think the set up might be a lot
