### ISSUE TITLE
Fix: Button needs a min-height first in the row

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#128]
### Type of feature

🐛 Fix

### Current behavior

When the "load more" button is the first item in the list the height does not match.

Not the first item.
<img width="987" alt="Screen Shot 2022-02-21 at 1 06 21 PM" src="https://user-images.githubusercontent.com/5713670/155026363-12d336cb-64f9-447e-a735-a090567826ca.png">

As the first item.
<img width="1348" alt="Screen Shot 2022-02-21 at 1 00 10 PM" src="https://user-images.githubusercontent.com/5713670/155026367-f7c504cb-f03d-4653-9d3c-5ea43ac2284f.png">

### Suggested solution

Add a CSS check to apply either a min-height or height (or similar). 

<img width="1320" alt="Screen Shot 2022-02-21 at 1 08 55 PM" src="https://user-images.githubusercontent.com/5713670/155026531-3e2eb730-0287-405c-9213-0b11b49cb0b6.png">

### Additional context

Please include screenshots in your PR. This was introduced in this PR https://github.com/open-sauced/hot/pull/127#issuecomment-1047225606

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nulfrost** [comment]
.take
