### ISSUE TITLE
Bug: When loading more items list gets unordered for a second.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#129]
### Describe the bug

When loading more items list gets unordered for a second.

### Steps to reproduce

1. Visit hot.opensauced.pizza
2. Scroll to the bottom and click "Load more"
3. Not the quick unordered list

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Additional context

First discovered in https://github.com/open-sauced/hot/pull/127#issuecomment-1047225606

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Not sure if this happening. Recorded my screen and slowed it down a bit. cc/ @0-vortex 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5713670/155028560-50939018-2661-4c0c-b464-45ba09db8825.gif)

**Comment by 0-vortex** [comment]
> Not sure if this happening. Recorded my screen and slowed it down a bit. cc/ @0-vortex
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/5713670/155028560-50939018-2661-4c0c-b464-45ba09db8825.gif)

That's what I was describing in the PR from the deploy preview. I'm guessing it's the sort on the items being handled for tabs, whereas the "load more" action should just push additional items to the tab without re-ordering :D

**Comment by 0-vortex** [comment]
Got a fix for this, could do a beta and check everything works after `.take`ing :D
