### ISSUE TITLE
Create Users submissions table

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#131]
This will require someone with Supabase access to create the table and migration. 

## Details

- [x] Create a table for user submissions
- [ ] Create a database.js funciton to upvote the submitted repo
- [ ] Check if the repo already exist in the DB before adding. 

## Question
Should the user still be associated to the submission?

We will need to wait on https://github.com/open-sauced/hot/pull/122

**Comment by 0-vortex** [comment]
This is handled by https://github.com/open-sauced/api.opensauced.pizza/issues/5 and the table structure is added in there
