### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#133]
## Story
As a user I want to view my profile and add links to my contributions. 

## Details

- [x] #134
- [x] #135
- [ ] Implement contribution activity component
- [ ] Implement backend logic for badges
- [ ] Discuss badges for user interactions (keep it simple)
- [ ] Connect Profiles to  GitHub user data (i.e. location)

## Design Mock
![image (2)](https://user-images.githubusercontent.com/5713670/155473994-de21d46d-9748-4251-a992-32f4c8e6863c.png)

**Comment by 0-vortex** [comment]
https://github.com/open-sauced/hot/issues/134 is technically existing but maybe it doesn't have all the infos we need
