### ISSUE TITLE
Feature: Implement prettier linting in this project

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#14]
### Type of feature

CI

### Current behavior

Currently, it is free for all and with our first contribution, I am seeing inconsistencies. I would love to mimic the code style in [open-sauced](https://github.com/open-sauced/open-sauced)

This came up in this PR https://github.com/open-sauced/hot-sauce/pulls

### Desired solution

- https://github.com/open-sauced/open-sauced/blob/main/.eslintrc.js
- https://github.com/open-sauced/open-sauced/blob/main/.stylelintrc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelvinsekx** [comment]
.take

**Comment by bdougie** [comment]
Hey @kelvinsekx, I unassigned you since you are currently assigned to half the open issues already. If you could assist with #15. That is a higher priority than this.

**Comment by kelvinsekx** [comment]
Power is down on my side, but I can do that through my phone. I just added the font-awesome.
