### ISSUE TITLE
Feature: Introduce Radix Primitives into the app. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#141]
### Type of feature

🍕 Feature

### Current behavior

After some discussion, the Open Sauced came to the conclusion that we need a design system ensure quality and consistency. So far items have been introduced ad hoc and styled by individuals. 

Moving forward we will centralize on [radix](https://www.radix-ui.com/docs/primitive) + [tailwind](https://tailwindcss.com/) for UI components. 

### Suggested solution

There is a [tailwind radix library](https://www.npmjs.com/package/tailwindcss-radix) that I would love to see included in this project. The focus for this issue should be installing the project and updating only 1 component for review. 

My suggestion is either [Avatars](https://tailwindcss-radix.vercel.app/#avatar) or [Tootips](https://tailwindcss-radix.vercel.app/#tooltip). - https://tailwindcss-radix.vercel.app/

### Additional context

Please only contribute to one component change per PR. The scope should stay small enough to review. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Going to `.take` this one 🍕

**Comment by hokagedemehin** [comment]
I think it will make sense to merge PR #140 before you make a PR for this one. Not that it's compulsory, just makes sense that's all

**Comment by 0-vortex** [comment]
> I think it will make sense to merge PR #140 before you make a PR for this one. Not that it's compulsory, just makes sense that's all

It's dropping tonight :D

**Comment by nulfrost** [comment]
sweet, I love radix and tailwind! accessibility out of the box will help a ton

**Comment by 0-vortex** [comment]
> sweet, I love radix and tailwind! accessibility out of the box will help a ton

lighthouse score 100 incoming! 🍕

**Comment by bdougie** [comment]
Moving forward we can approach UI this way:

1. [Radix primitives ](https://www.radix-ui.com/)for what is available
2. [Headless UI ](https://headlessui.dev/)for what is not available in Radix

Though I do want to explore [radix-tailwind ](https://tailwindcss-radix.vercel.app/)but not ready to commit to that.

**Comment by 0-vortex** [comment]
> Moving forward we can approach UI in the following order:
> 
> 1. [Radix primitives ](https://www.radix-ui.com/)for what is available
> 2. [Headless UI ](https://headlessui.dev/)for what is not available in Radix
> 3. [Reach UI](https://reach.tech/)
> 
> Though I do want to explore [radix-tailwind ](https://tailwindcss-radix.vercel.app/)but not ready to commit to that.

Commit to radix primitives, the tailwind connector is just a helper library we can ultimately do without! 🍕

**Comment by bdougie** [comment]
We have already begin using radix. For those new to contributing components, we can point them to this issue. FYI, @shamimbinnur
