### ISSUE TITLE
Feature: decouple supabase into a fully-fledged backend

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#146]
### Type of feature

🍕 Feature

### Current behavior

**Description:** 
Hot open sauced was supposed to be a weekend mockup that we use to mockup several features into open sauced however it turned the other way around and now it is in need of some minor architecture changes. 

Due to the above experimental nature, we created loose database configurations that were initially flat data but ultimately turned into a database and our credentials to that database are essentially public in the code.

**Issue:** 
Not leaking credentials and having a full-stack [Supabase](https://supabase.com/docs/guides/with-nextjs) app in one repository requires us to use [Row Level Security](https://supabase.com/docs/learn/auth-deep-dive/auth-row-level-security) and service tokens that do not write data, moving that logic into (potentially?) Supabase functions.

### Suggested solution

Not relying too much on one product and still keeping the party running with our existing decisions, we should wrap a small but useful layer around our current described full-stack usage into another more secure service.

Start using [RedwoodJS](https://redwoodjs.com/docs/introduction) with [Supabase](https://supabase.com/docs/guides/with-redwoodjs), split everything related to the backend into api.opensauced.pizza, and bring the functionality closer to original open sauced experience in terms of security and GraphQL client queries.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
This PR calls for a different solution for #136 and invalidates #139

**Comment by bdougie** [comment]
This is 💯  the future and direction we are headed. My only reservation is another rewrite would delay potential user adoption by a month. My question is when we enable RLS for Supabase and completed the planned UI clean-up, would this project be ready for prime time without the RedwoodJs and Supabase updates?

The plan:
1. Launch new landing page for opensauced.pizza with some clear features and offerings.
2. Launch hot.opensauced.pizza for public consumption and user growth/adoption. 
3. Refresh opensauced.pizza UI and switch to app.opensauced.pizza
4. Connect supabase to a new redwoodjs app with the goal for enhance security and cleaner DB interactions.

**Comment by bdougie** [comment]
Update: We don't need to explore the Redwood switch per the conversations in discord last month. We have also started the process towards NestJS - https://github.com/open-sauced/api.opensauced.pizza

**Comment by 0-vortex** [comment]
Tracked as individual issues in [api.opensauced.pizza](https://github.com/open-sauced/api.opensauced.pizza) 🍕
