### ISSUE TITLE
Feature: re-implement dark mode and toggle

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#150]
### Type of feature

🍕 Feature

### Current behavior

Dark mode is not enabled

### Suggested solution

Use [Tailwind - Toggling dark mode manually](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) with a react hook IE:
- https://github.com/open-sauced/open-sauced/blob/eb1bb9030cbc0bba6d883d5ed933e99f5488ea14/src/containers/App.jsx#L48-L72
- https://github.com/juniHub/try-not-to-laugh-challenge/tree/master/src/components

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by kelvinsekx** [comment]
.take

**Comment by TAKANOME-DEV** [comment]
Hey @kelvinsekx  do you need some help??

**Comment by bdougie** [comment]
Going to unassign this one. @TAKANOME-DEV is you are still around feel free to take a look, but also understand this is also blocked by this PR. https://github.com/open-sauced/hot/pull/189

**Comment by TAKANOME-DEV** [comment]
Yeah for sure, I am going to give it a shot

**Comment by bdougie** [comment]
This feature needs design per #201
