### ISSUE TITLE
Bug: Posthog not sending analytics data

### ISSUE THREAD

**Issue by chadstewart** [open-sauced/hot#157]
### Describe the bug

Posthog won't send analytics data from the app

### Steps to reproduce

Run the application and click on any upvote button or the login button.

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Hey, the env variable needs to be set in the repo settings, that was a step @bdougie was supposed to do before merging :D I can add it as well now that I am on but didn't merge yesterday because I didn't know what value it should have :D

**Comment by chadstewart** [comment]
> Hey, the env variable needs to be set in the repo settings, that was a step @bdougie was supposed to do before merging :D I can add it as well now that I am on but didn't merge yesterday because I didn't know what value it should have :D

I believe the .env variable was set but I didn't know that the variable needed the prefix 'VITE_' to be exposed by vite to be exposed by Vite. Honestly, this work taught me a bit about Vite but I'm also not sure about the fix I did for this issue. 😅
