### ISSUE TITLE
Bug: improper use of any types

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#162]
### Describe the bug

<any> is used in too many places, the beta -> main deploy wasn't cleaned up properly

### Steps to reproduce

npm run lint

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by mtfoley** [comment]
i sent a PR with a little feature baked in.
.take
