### ISSUE TITLE
Bug: filtering doesn't work after v2.3.0

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#163]
### Describe the bug

filtering doesn't work

### Steps to reproduce

go to https://hot.opensauced.pizza and click any of the top bar tabs, only "my votes" and "popular" buttons filter and order properly

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by mtfoley** [comment]
FWIW, here's how the fetchRecommendations payloads break down at the moment:

They all share the same ordering attributes.
`order`=`stars.desc.nullslast,updated_at.desc.nullslast`
`contributions.order`=`last_merged_at.desc.nullslast`

BaseSelect=`id,full_name,description,stars,issues,starsRelation:users_to_repos_stars(starsCount:count),votesRelation:users_to_repos_votes(votesCount:count),contributions(last_merged_at,contributor,url,prsCount:count)`

| Button | Select |
| --- | --- |
| Popular | `BaseSelect` |
| Upvoted | `BaseSelect` + `,votes:users_to_repos_votes!inner(*)` |
| Discussed | `BaseSelect` |
| Recent | `BaseSelect` |
| My Votes | `BaseSelect` + `,myVotesRelation:users_to_repos_votes!inner(myVotesCount:count),myVotesFilter:users_to_repos_votes!inner(user_id)` |

Still looking to see if there's some client side sorting that happens.

**Comment by 0-vortex** [comment]
Nothing client side, ditching PostgRest ASAP :D also, working on this so I should `.take` it 💯
