### ISSUE TITLE
Feature: Filtering should be reflected in the URL

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#167]
### Type of feature

🍕 Feature

### Current behavior

When selecting a filter it requests new data from the API (supabase for now). It should provide the filter in the URL. i.e. `hot.opensauced.pizza?filter=upvoted`. The default can still be popular, but it should also respect the URL 👉🏾`hot.opensauced.pizza?filter=popular`

### Suggested solution

Use next.js to add query params. 

### Additional context

https://nextjs.org/docs/routing/dynamic-routes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
We should confirm that this is fixed first. https://github.com/open-sauced/hot/issues/163

**Comment by 0-vortex** [comment]
> We should confirm that this is fixed first. #163

Routes can be implemented without database filtering actually working, we should add a header or a text description of what the users are seeing with a specific filter above the repo grid/list, that way we can make routing and URL parameter translations work from navigation links, pass those prop(s) over to the fetch function when filtering/ordering works on the backend level. IMHO just implementing the routes like that could make for a good first issue as we the minimal implementation would just require reading up on https://reactrouter.com and how to clone and start the repo 🍕

**Comment by TAKANOME-DEV** [comment]
Hey folks, can I take afetr #163 is fixed??

**Comment by htuerker** [comment]
.take
