### ISSUE TITLE
Feature: Replace placeholder image with repo social card 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#17]
### Type of feature

Feature

### Current behavior

Prior to #13, this app was pulling in the social cards from GitHub. 

https://github.com/open-sauced/hot-sauce/blob/main/src/components/SocialImage.jsx

This is the previous fetching of the social card image. 

https://github.com/open-sauced/hot-sauce/blob/c3e28250cc27ee7b43b5134b1e883bc8c2864338/src/pages/index.astro#L14-L21

Previous PR where this was working https://github.com/open-sauced/hot-sauce/pull/1/files

### Desired solution

Add the social image in replace of the placeholder. See the previous PR where this was:
![Screen Shot 2021-12-17 at 4 55 20 PM](https://user-images.githubusercontent.com/5713670/146612481-77e526ad-54e2-4a64-a145-27eeb6402fc0.png)

Example pulling images from open graph.

![Group 2](https://user-images.githubusercontent.com/5713670/146612578-5501f29d-5665-4fa1-b8a0-3ccf216f71a3.png)

### Additional context

[Previous site with social card
](https://4000735cf7f--hot-sauced-ui.netlify.app)
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdougie** [comment]
@NaaLaryea do you want to look into this?

**Comment by NaaLaryea** [comment]
yes i do

**Comment by NaaLaryea** [comment]
.take

**Comment by bdougie** [comment]
Checking in @NaaLaryea to see if you have any questions don't this.

**Comment by hokagedemehin** [comment]
.take

**Comment by hokagedemehin** [comment]
I have found a possible solution to this issue. I will implement and share it with you later today

**Comment by kelvinsekx** [comment]
I will love to see your solution.
 However, @NaaLaryea is assigned to this already. And I would have loved to hear her feedback on this. Just to avoid conflicts

**Comment by NaaLaryea** [comment]
Hi @kelvinsekx so sorry I have MIA, been battling covid so I have been slow, trying to recover. Do merge his if it fixes the issue. I will pick up work soon.

**Comment by 0-vortex** [comment]
> Hi @kelvinsekx so sorry I have MIA, been battling covid so I have been slow, trying to recover. Do merge his if it fixes the issue. I will pick up work soon.

Hope you get well easily!

**Comment by kelvinsekx** [comment]
> Hi @kelvinsekx so sorry I have MIA, been battling covid so I have been slow, trying to recover. Do merge his if it fixes the issue. I will pick up work soon.

Get well soon dear ❤️

**Comment by hokagedemehin** [comment]
> Hi @kelvinsekx so sorry I have MIA, been battling covid so I have been slow, trying to recover. Do merge his if it fixes the issue. I will pick up work soon.

Get well soon 🤗🤗
