### ISSUE TITLE
Feature: Add carrot to search results

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#172]
### Type of feature

🍕 Feature

### Current behavior

Currently, live on the beta branch there is a search functionality
<img width="682" alt="Screen Shot 2022-05-26 at 6 18 16 AM" src="https://user-images.githubusercontent.com/5713670/170496066-87f46381-add2-43cd-882c-cb7d6305adb6.png">
y

### Suggested solution

This should be straightforward and use font awesome icons. 

https://fontawesome.com/icons/chevron-right?s=solid

<img width="1482" alt="Screen Shot 2022-05-26 at 6 19 54 AM" src="https://user-images.githubusercontent.com/5713670/170496261-7340764c-00a2-4f40-90d4-f284160604a3.png">
 

### Additional context

examples of font awesome usage https://github.com/open-sauced/hot/blob/570f10f7a26b19d950ed6bf9a5d89e1233fb5c33/src/components/LayoutToggle.tsx#L2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Mrityunjay1** [comment]
Hello, Can i work on this.
Adding carrot if you can give a brief about it. That would be great.

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by htuerker** [comment]
Hope this works! 
.take

**Comment by htuerker** [comment]
.take

**Comment by mtfoley** [comment]
Hi @htuerker  it looks like the "take action" thing is broken upstream. I'm assigning you on this one and filing a bug there.

**Comment by htuerker** [comment]
> Hi @htuerker it looks like the "take action" thing is broken upstream. I'm assigning you on this one and filing a bug there.

I was about to look for a solution on the discord channel. Thanks, I'm going to work on this!
