### ISSUE TITLE
Feature: update last commit date to dayjs moment

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#174]
### Type of feature

🍕 Feature

### Current behavior

When hovering over contributors the date format presents a date string. This should be presented in moment content. 

i.e. "2 days ago"

![Screen Shot 2022-05-26 at 1 22 43 PM](https://user-images.githubusercontent.com/5713670/170574481-821877e1-d3cb-4027-a92c-646c362c637e.png)

### Suggested solution

Install [dayJS](https://day.js.org/) - https://day.js.org/docs/en/display/from-now

This can be implement in this file on this line https://github.com/open-sauced/hot/blob/main/src/components/Avatar.tsx#L68

### Additional context

We could also use node for this https://dev.to/github/learn-how-the-javascript-advances-datetime-with-proposal-temporal-59hf

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by mtfoley** [comment]
as I've learned at work lately, the relative format is better from an a11y standpoint as well.

another approach (if the value can be passed as a Date object) might be to just do the subtraction so you don' t need to install anything: 
```js
function relativeAge(value){
  if(!value instanceof Date) value = new Date(value);
  const now = new Date(),
    diff = (now-value),
    second = 1000, // in milliseconds
    minute = 60*second,
    hour = 60*minute,
    day = 24*hour;
  let unit, rounded;
  if(diff < minute){
    unit = "second";
    rounded = Math.floor(diff/second);
  } else if (diff < hour) {
    unit = "minute";
    rounded = Math.floor(diff/minute);
  } else if (diff < day) {
    unit = "hour";
    rounded = Math.floor(diff/hour);
  } else {
    unit = "day";
    rounded = Math.floor(diff/day);
  }
  // e.g. 7 seconds ago
  return `${rounded} ${unit}${rounded === 1 ? "" : "s"} ago`;
}
```

**Comment by 0-vortex** [comment]
> as I've learned at work lately, the relative format is better from an a11y standpoint as well.
> 
> another approach (if the value can be passed as a Date object) might be to just do the subtraction so you don' t need to install anything:
> 
> ```js
> function relativeAge(value){
>   if(!value instanceof Date) value = new Date(value);
>   const now = new Date(),
>     diff = (now-value),
>     second = 1000, // in milliseconds
>     minute = 60*second,
>     hour = 60*minute,
>     day = 24*hour;
>   let unit, rounded;
>   if(diff < minute){
>     unit = "second";
>     rounded = Math.floor(diff/second);
>   } else if (diff < hour) {
>     unit = "minute";
>     rounded = Math.floor(diff/minute);
>   } else if (diff < day) {
>     unit = "hour";
>     rounded = Math.floor(diff/hour);
>   } else {
>     unit = "day";
>     rounded = Math.floor(diff/day);
>   }
>   // e.g. 7 seconds ago
>   return `${rounded} ${unit}${rounded === 1 ? "" : "s"} ago`;
> }
> ```

The date is saved in the database as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) or [PG TIMESTAMP WITHOUT TIME ZONE](https://www.postgresql.org/docs/current/datatype-datetime.html). We can have conversions in potentially 3 layers: 
- how we store dates
- how we retrieve dates from the backend
- how we parse dates on the client

**Comment by mtfoley** [comment]
if it's the "last_merged_at" field I'm seeing in the network requests, I think we'd only need to put "+00:00" on the end of it so that the JS Date constructor (or `Date.parse`) would consider it to be UTC and do the differential correctly.

<img width="363" alt="Screen Shot 2022-05-27 at 1 55 14 PM" src="https://user-images.githubusercontent.com/3792749/170765167-c602f970-49ab-4e95-b088-223049a39b80.png">

**Comment by ABeck617** [comment]
Good Morning I would like to tackle this issue

**Comment by ABeck617** [comment]
".take"

**Comment by blackgirlbytes** [comment]
Hey @ABeck617 i figured it out. here's what we have to do:

for the imports

```import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);
```

for the conversion to relative time
``` lastPr={dayjs(data.contributions[1]?.last_merged_at).fromNow()}/>} ```

I think you only have availability to meet on Thursday but if you have time earlier ..I'm down too. This should take us less than 30 minutes
