### ISSUE TITLE
Feature: Add card component to grid showcase

### ISSUE THREAD

**Issue by htuerker** [open-sauced/hot#182]
### Type of feature

🍕 Feature

### Current behavior

In the recommendations grid, we're using an image not a real component. 

For this reason, it's hard to add additional features to it such as giving direct links to access information data shown on the image.

![Screen Shot 2022-06-13 at 17 50 46](https://user-images.githubusercontent.com/46192266/173381977-d91d9500-102c-4a11-b63b-8e524b7c3248.png)

In addition, there are some requests failing with status code 429(too many reqs)
![Screen Shot 2022-06-13 at 18 08 32](https://user-images.githubusercontent.com/46192266/173385259-a144e96f-78c7-4691-9f06-a9b1aae412b8.png)

 

### Suggested solution

We already have fetched all the required information so there's no extra cost to use our own component rather than using an image generated by opengraph.githubassets.com

Here's is the current corresponding code: 
https://github.com/open-sauced/hot/blob/f1517c294c3d2c635ec6de084d5bd0c0489cdaff/src/components/PostGrid.tsx#L73-L77

- Instead of using an image representation, create a card component here

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This will be covered in the work in https://github.com/open-sauced/hot/milestone/2
