### ISSUE TITLE
Feature: Add improvements to Avatar / Date Component

### ISSUE THREAD

**Issue by blackgirlbytes** [open-sauced/hot#186]
### Type of feature

🧑‍💻 Refactor

### Current behavior

I helped someone making their first open source contribution, but there are some improvement needed for it. Right now, in beta
- It says "Last contribution at [insert relative time] " --> I need to remove the at
- It needs tests
- Storybook needs to be updated

### Suggested solution

see above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by blackgirlbytes** [comment]
.take

**Comment by 0-vortex** [comment]
I removed the `at ` part btw :D

**Comment by htuerker** [comment]
Would you like to handle #188 in the scope of your work? @blackgirlbytes

**Comment by blackgirlbytes** [comment]
sure @htuerker !!! :)  thank you!
