### ISSUE TITLE
Feature: Move the search debounce logic to its own hook

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#196]
### Type of feature

🧑‍💻 Refactor

### Current behavior

After some discovery looking for components that need testing, I saw that this logic was not moved and it needs to be to keep all components flexible and reusable. 

https://github.com/open-sauced/hot/blob/main/src/components/PrimaryNav.tsx#L19-L38

### Suggested solution

1. Move this debounce function to a hook
2. Tests are required for this contribution.  

### Additional context

https://kentcdodds.com/blog/how-to-test-custom-react-hooks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
This is solved by `rooks`
