### ISSUE TITLE
Feature: New Hero

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#200]
### Type of feature

🍕 Feature

### Current behavior

Currently everything above the fold provides no context on the project. 

<img width="1187" alt="Screen Shot 2022-07-15 at 6 22 28 AM" src="https://user-images.githubusercontent.com/5713670/179232857-6d097186-31cf-4b94-bdfd-0e10e89ac0f0.png">

We have no hero to provide search and a H1.

### Suggested solution

<img width="975" alt="Screen Shot 2022-07-15 at 6 23 07 AM" src="https://user-images.githubusercontent.com/5713670/179231863-44c1823a-897d-46e1-9157-5afbadab3adf.png">

- [ ] Sub nav will be hidden for now. Remove component from page bug keep the component in the project
- [ ] Search box will now live in the hero and be removed from the Nav
- [ ] #205

Link to [figma](https://www.figma.com/file/Rrc4Bc5lFoyDOrvD00ThkB/bdougie---new-hot.opensauced?node-id=0%3A1)

### Additional context

password to figma is secretsauce

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hokagedemehin** [comment]
.take

**Comment by pixelsbyeryc** [comment]
@bdougie does it make sense to have a search box when the nav scrolls down?

**Comment by bdougie** [comment]
It would be nice for it to pin when the sue scrolls. Happy to see a design, but I would scope that on a new issue.

**Comment by bdougie** [comment]
@hokagedemehin going to I assign you since this work will need to ship alongside #201. Can you grab one of the card update issues instead?

**Comment by hokagedemehin** [comment]
I will take #202 if that is fine
