### ISSUE TITLE
Feature: UI updated nav 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#201]
### Type of feature

🍕 Feature

### Current behavior

<img width="1677" alt="Screen Shot 2022-07-15 at 6 22 34 AM" src="https://user-images.githubusercontent.com/5713670/179231956-2c7f5ac8-fd75-4544-8152-fafc1786e208.png">

1. Search box needs to move
2. New logo
3. Login is now a button

### Suggested solution

Update nav 
- [ ] Votes link in the header
- [ ] New sign in button
- [ ] New logo and wordmark (separated)

Keep in mind "my votes" will need to be shown only when logged in.

Right side of the nav

<img width="293" alt="Screen Shot 2022-07-15 at 6 32 44 AM" src="https://user-images.githubusercontent.com/5713670/179233494-6488fc34-1386-46c0-927b-88e7958182f4.png">

Left side of the nav
<img width="517" alt="Screen Shot 2022-07-15 at 6 32 40 AM" src="https://user-images.githubusercontent.com/5713670/179233509-f4596d05-fbd1-411d-96f6-451a4fc9f790.png">

Link to [figma](https://www.figma.com/file/Rrc4Bc5lFoyDOrvD00ThkB/bdougie---new-hot.opensauced?node-id=0%3A1)
 
related https://github.com/open-sauced/hot/issues/200

### Additional context

password to figma is secretsauce

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by pixelsbyeryc** [comment]
@shamimbinnur @bdougie do we have the **search results** box, or should I create the designs for that as well?

**Comment by shamimbinnur** [comment]
> @shamimbinnur @bdougie do we have the **search results** box, or should I create the designs for that as well?

@pixelsbyeryc We already have the mockup for that, as you can see on the preview deployment(Not completed yet)
But I believe you can come up with a great design for this 😊

**Comment by pixelsbyeryc** [comment]
@shamimbinnur let's go with the mockup we already have then, and if need be, we can open another issue to cover for that. Thank you! 🚀
