### ISSUE TITLE
Feature: New hot cards

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#202]
### Type of feature

🍕 Feature

### Current behavior

Currently cards are shown in PostGrid view and PostList view. We are removing that toggle and showing the hottest repos in PostGrid view and update the list to be shown with all repos listed. 

### Suggested solution

Please remove the sub-nav from the page and replace that with the "hot card" section. There will only be 3 cards listed, which we can do this statically in the component. We can mock the data for. 

Please render these 3 repos as hot repos. 
1. [oven-sh/bun](https://github.com/oven-sh/bun)
2. [pocketbase/pocketbase](https://github.com/pocketbase/pocketbase)
3. [open-sauced/open-sauced](https://github.com/open-sauced/open-sauced)

<img width="873" alt="Screen Shot 2022-07-15 at 6 37 02 AM" src="https://user-images.githubusercontent.com/5713670/179235262-bdc550ed-41ba-4620-b206-473a672fda86.png">

Link to [figma](https://www.figma.com/file/Rrc4Bc5lFoyDOrvD00ThkB/bdougie---new-hot.opensauced?node-id=0%3A1)

### Additional context

password to figma is secretsauce

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by pixelsbyeryc** [comment]
Here's the "voted" state for the "Upvote" button. We can change the copy, that's just a placeholder.

<img width="537" alt="Screen Shot 2022-07-15 at 11 58 59 PM" src="https://user-images.githubusercontent.com/101464991/179336685-23c46dd1-15df-4a5c-8c73-a4c7baa8b6a8.png">

**Comment by hokagedemehin** [comment]
.take
