### ISSUE TITLE
Feature: Contributor lists hover effect.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#204]
### Type of feature

🍕 Feature

### Current behavior

On the changes in #189 we now include 5 contributors with a link to see more. Instead we will remove the link and create a hover effect to show them.

### Suggested solution

No hover
<img width="77" alt="Screen Shot 2022-07-15 at 6 37 49 AM" src="https://user-images.githubusercontent.com/5713670/179236800-32894bbf-7a0b-4cbc-a7c0-445822eb39cd.png">

With Hover
<img width="246" alt="Screen Shot 2022-07-15 at 6 52 04 AM" src="https://user-images.githubusercontent.com/5713670/179237006-9567ebd2-a96c-43de-ae26-e97b57518222.png">

To see this live, visit [app.opensauced.pizza/repos/vercel/next.js](https://app.opensauced.pizza/repos/vercel/next.js) and hove over a issue with multiple contributors. 

Link to [figma](https://www.figma.com/file/Rrc4Bc5lFoyDOrvD00ThkB/bdougie---new-hot.opensauced?node-id=0%3A1)

### Additional context

password to figma is secretsauce

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by pixelsbyeryc** [comment]
Made a working prototype to show how this interaction should work:

[View in Figma](https://www.figma.com/proto/z0LEHrTwmvuCokhbYmIhPd/OpenSauced-%E2%80%94-Hot-(hot.opensauced.pizza)?page-id=184%3A38&node-id=184%3A66&viewport=78%2C373%2C1.02&scaling=min-zoom&starting-point-node-id=184%3A66)

**Tooltip CSS** (Use the "Inspect" tab in Figma to view this CSS):
```css

/* Font Styles */
font-family: 'Inter';
font-style: normal;
font-weight: 500;
font-size: 10px;
line-height: 100%;
color: #ECEDEE; /* dark/slate/12 */

/* Box Styles */
padding: 4px 8px;
background: #1A1D1E; /* dark/slate/02 */
border: 1px solid #313538; /* dark/slate/06 */
box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.1), 0px 1px 2px rgba(0, 0, 0, 0.1);
border-radius: 4px;
```

**Comment by bdougie** [comment]
Note that this has been approached by @hokagedemehin in https://github.com/open-sauced/hot/pull/216. Though it could use some polish with animation.

Whoever ends up picking this, keep that in mind.
