### ISSUE TITLE
Search will have command+K option to show search.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#205]
This work should be done in a separate PR from #200. We will need to implement using command + K or Ctrl + K to open the search box. I am sure there is a plugin for keyboard commands, but have not done the research. 

This work cannot merge without #200

![new hero](https://user-images.githubusercontent.com/5713670/179231863-44c1823a-897d-46e1-9157-5afbadab3adf.png)

**Comment by ddsuhaimi** [comment]
Just wanna recommend a package, I use [react-hot-keys](https://www.npmjs.com/package/react-hot-keys) in one of my projects and it works well so far.

**Comment by ddsuhaimi** [comment]
@bdougie I can work on this one, but what do you mean by opening the search box? the input should just be focused when user  press CTRL + K right?

**Comment by 0-vortex** [comment]
> @bdougie I can work on this one, but what do you mean by opening the search box? the input should just be focused when user press CTRL + K right?

We have the `rooks` package installed, this ticket should be an implementation of https://react-hooks.org/docs/useKeyBindings linking the `cmd/ctrl+k` shortcut to the existing event handler on the search box 🍕

**Comment by ddsuhaimi** [comment]
@0-vortex I see, just to confirm. If user press cmd/ctrl+k then the search box will open up like this, right? So user can type immediately.

![image](https://user-images.githubusercontent.com/30659198/181429658-f26bd676-c1a3-4ce2-87ea-a72a4f227ab7.png)

**Comment by shamimbinnur** [comment]
@ddsuhaimi this issue is already assigned to me :)

**Comment by 0-vortex** [comment]
> @ddsuhaimi this issue is already assigned to me :)

I don't see a problem with 2 people working on the same issue, as long as they coordinate accordingly. I see you have an open PR @shamimbinnur, do you have any work done on this issue? 

If not, it would be best to let someone else do it if they are willing to, in order to discourage a "dibs" like scenario. We want to prevent scope creeping and as such, we generally assign 1 issue at a time unless the complexity demands a specific maintainer/contributor.

Let me know if there are other ways I can help!

**Comment by shamimbinnur** [comment]
> > @ddsuhaimi this issue is already assigned to me :)
> 
> I don't see a problem with 2 people working on the same issue, as long as they coordinate accordingly. I see you have an open PR @shamimbinnur, do you have any work done on this issue?
> 
> If not, it would be best to let someone else do it if they are willing to, in order to discourage a "dibs" like scenario. We want to prevent scope creeping and as such, we generally assign 1 issue at a time unless the complexity demands a specific maintainer/contributor.
> 
> Let me know if there are other ways I can help!

@0-vortex I was working on this issue while I was working on the hero. But as this issue was asked to solve on separate PR. I stopped there and waited to be merged. No problem if @ddsuhaimi takes this over now.

**Comment by ddsuhaimi** [comment]
@shamimbinnur oops sorry, didn't realize it was taken already

okay, I will work on this
