### ISSUE TITLE
Add ability to report bugs from the user dropdown

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#206]
There should be a link to "report a bug" that links to https://github.com/open-sauced/hot/issues/new?assignees=&labels=%F0%9F%91%80+needs+triage%2C%F0%9F%90%9B+bug&template=bug_report.yml&title=Bug%3A+

![Image](https://user-images.githubusercontent.com/5713670/179242025-13ac7182-c97c-4368-9cba-b7751c0b4188.png)

**Comment by ddsuhaimi** [comment]
.take
