### ISSUE TITLE
Test: write test for dayjs

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#207]
### Type of feature

✅ Test

### Current behavior

The DayJS was added to the avatar component in #199. The logic is baked in and will be challenging to test. 

### Suggested solution

1. Move dayjs to a lib/day.js
2. Test dayjs in isolation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by SunGoldTech** [comment]
.take
