### ISSUE TITLE
Bug: My Votes Tab is Empty if you have never voted before

### ISSUE THREAD

**Issue by hokagedemehin** [open-sauced/hot#208]
### Describe the bug

My Votes tab is empty if you have never voted before.

There could be a placeholder illustration there to say that this page is empty because you have not voted before or something

What do you think?

### Steps to reproduce

1. Go to [http://localhost:3000/](localhost)
2. Click on My Votes (If you have never voted before)
3. Page will be empty

### Screenshot
![Screenshot 2022-07-15 235914](https://user-images.githubusercontent.com/16826624/179324008-54662df1-8e81-457b-ba2c-9c1d8346b3b1.png)

### Affected services

hot.opensauced.pizza

### Platforms

Desktop, Mobile

### Browsers

Chrome

### Environment

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
good catch, some kind of status message should be displayed when returned repositories is 0 from the backend, in all the tabs actually!
