### ISSUE TITLE
Design: search box when the nav scrolls

### ISSUE THREAD

**Issue by pixelsbyeryc** [open-sauced/hot#209]
When the nav scrolls, or when the user is in an internal page, show the search bar on the nav.

__Originally posted by @pixelsbyeryc in https://github.com/open-sauced/hot/issues/200#issuecomment-1186074822__

**Comment by pixelsbyeryc** [comment]
.take

**Comment by pixelsbyeryc** [comment]
## What's updating:
- How the navbar will look when scrolled
- What the searchbox will look like in the navbar

### How the navbar will look when scrolled

- [Figma Link](https://www.figma.com/file/z0LEHrTwmvuCokhbYmIhPd/OpenSauced-%E2%80%94-Hot-(hot.opensauced.pizza)?node-id=212%3A376): You can inspect the CSS and styles from here
- [Figma Prototype](https://www.figma.com/proto/z0LEHrTwmvuCokhbYmIhPd/OpenSauced-%E2%80%94-Hot-(hot.opensauced.pizza)?page-id=212%3A375&node-id=212%3A376&viewport=400%2C446%2C0.32&scaling=min-zoom): You can scroll to view how the navbar will look like

Here's some CSS to help style the Navbar:
```css
background: rgba(255, 255, 255, 0.9);
/* light/slate/06 */

border-bottom: 1px solid #DFE3E6;
box-shadow: 0px 4px 16px rgba(49, 53, 56, 0.1);
backdrop-filter: blur(12px);
```

**In case the `backdrop-filter` is not supported, we should keep the `background` with no opacity.**

**Navbar Structure**

<img width="1201" alt="Screen Shot 2022-07-19 at 9 32 21 PM" src="https://user-images.githubusercontent.com/101464991/179870661-09ce3ae0-49fd-4c24-8786-ed584ad3ecf8.png">

**Navbar Preview on Page**

<img width="1146" alt="Screen Shot 2022-07-19 at 9 32 52 PM" src="https://user-images.githubusercontent.com/101464991/179870708-b43217a1-2308-4100-bc8c-e6622e87ada0.png">

### Search Box

States:
- Default
- Default with Text: text color will be darker
- Hover: Background updates one step darker
- Focus: Border turns orange, and we add an orange `ring`

The Shortcut button will also update from "CMD+K" to "Enter" symbol. Since we're all power-users, we don't have the need to label the shortcut symbols.

<img width="1059" alt="Screen Shot 2022-07-19 at 9 42 31 PM" src="https://user-images.githubusercontent.com/101464991/179871520-37444f14-95c1-4212-84ea-6c48bad26c85.png">

**Comment by pixelsbyeryc** [comment]
@bdougie do we need designs for the search results as well?

**Comment by pixelsbyeryc** [comment]
Implementation: #201

**Comment by bdougie** [comment]
We have existing UI for that, that matches. Better to implement that and address it when we do a further discovery on the design.
