### ISSUE TITLE
Feature: Replace placeholder avatars with contributor avatars

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#21]
### Type of feature

Feature

### Current behavior

Within each repo card, the list avatars are placeholders. This was needed to figure out the design, but they will need to be replaced with the avatars of the contributors.

![image](https://user-images.githubusercontent.com/5713670/146656466-e899fe50-6a29-4052-ac23-a9296aae34ab.jpeg)

### Desired solution

In the opensauced.pizza app, we grab the avatars using graphql. We can do something similar here. 

Example in the opensauced dashboard

![image](https://user-images.githubusercontent.com/5713670/146656469-8d3b4d79-f851-4aea-b3b0-931e0a34dfb3.jpeg)

### Additional context

This can be completed without a github OAuth

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Update:

This issue is blocked on the need for a proper data fetching pattern from GitHub.
- [x] #23

**Comment by kelvinsekx** [comment]
Is there no link to fetch the Avatars?

**Comment by bdougie** [comment]
Yes and not. You can fetch the contributors of repository and you can fetch avatars using github usernames separately. 

Link to how it is done in the main repo: https://github.com/open-sauced/open-sauced/blob/bf2501d0320c282695b563e02b7394f871557d0d/src/components/Repository.js#L119

1. I think we will need to recreate this [persisted query](https://github.com/open-sauced/open-sauced/blob/6ac20a8b6d20b0edeb2fe0b01137ce5f7996117d/src/lib/persistedGraphQL.js#L48) file in this repository. 
2. We will introduce [data fetching from github](https://github.com/open-sauced/open-sauced/blob/bf2501d0320c282695b563e02b7394f871557d0d/src/components/Repository.js#L36-L56) in this project
3. Use the existing [contributors_oneGraph](https://github.com/open-sauced/open-sauced/blob/bf2501d0320c282695b563e02b7394f871557d0d/src/components/Repository.js#L104-L119) item to [display avatars](https://github.com/open-sauced/open-sauced/blob/bf2501d0320c282695b563e02b7394f871557d0d/src/components/Repository.js#L191-L209).

I will do the following to unblock this

- [ ]  Include the Open Sauced Persisted query data fetching and API from OneGraph

**Comment by nulfrost** [comment]
I'd love to take this one on once it's unblocked! So just to make sure I'm clear on what the task at hand is, we want to replace the placeholder avatars with avatars coming from the github api? Also since we are rendering a list of repos from a static list of items in a json file, would we be replacing that with the data from the github API or something else?

**Comment by bdougie** [comment]
> we want to replace the placeholder avatars with avatars coming from the github API?
The placeholder images should be actual avatars of the top 2 contributors of the project. 

> Also since we are rendering a list of repos from a static list of items in a json file, would we be replacing that with the data from the github API or something else?
The static file is temporary for development. This was a shorcut to avoid pagination of the https://api.opensauced.pizza.

**Comment by nulfrost** [comment]
Okay I see, gotcha! Will wait for that to be merged ☺️ thank you

**Comment by bdougie** [comment]
This is now unblocked, the data was added to the [static JSON](https://github.com/open-sauced/hot/blob/main/src/data/posts.json#L8) file. The avatars can now be dynamically rendered.

**Comment by nulfrost** [comment]
.take
