### ISSUE TITLE
Bug: Move SVGs out of the public folder

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#214]
### Describe the bug

SVGs should be added inline to the assets folder - https://github.com/open-sauced/hot/tree/main/src/assets. We run release build and the public folder is skipped from consideration during that process

![Screen Shot 2022-07-19 at 1 39 44 PM](https://user-images.githubusercontent.com/5713670/179844180-1cffdaf6-f60e-4606-8035-889dcc110575.png)

### Steps to reproduce

1. Switch to the beta branch to view the public folder
2. Note the logo SVG added there.

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
does it 64ba1749efe1500e84f5ab088fbf4442b0777786 fixes this issue ?

**Comment by shamimbinnur** [comment]
@bdougie does it 64ba1749efe1500e84f5ab088fbf4442b0777786 fixes this issue ?

**Comment by shamimbinnur** [comment]
@bdougie does it 64ba1749efe1500e84f5ab088fbf4442b0777786 fixe this issue ?

**Comment by shamimbinnur** [comment]
@bdougie does it 64ba1749efe1500e84f5ab088fbf4442b0777786 fix this issue ?

**Comment by 0-vortex** [comment]
Please don't close issues as completed before they hit the `main` branch. https://github.com/open-sauced/release is taking care of that for us, given we create proper pull requests 🍕

**Comment by 0-vortex** [comment]
There are still 2 images left over:
- https://github.com/open-sauced/hot/blob/beta/public/gradBG.svg
- https://github.com/open-sauced/hot/blob/beta/public/openSauced.svg
