### ISSUE TITLE
feature: Implement voting function in Hot section

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#218]
note: We have a function to make this work. This placeholder does not follow that pattern. Despite this being mocked data, we could still makes this work live.

_Originally posted by @bdougie in https://github.com/open-sauced/hot/pull/216#discussion_r927049498_

**Comment by hokagedemehin** [comment]
Hi @bdougie 

If I may ask, is the code block below the function you are talking about??

```js
  async function handleVoteUpdateByRepo(votes: number, repo_id: number) {
    user_id && capturePostHogAnayltics('User voted', 'voteClick', 'true');

    const updatedVotes = await updateVotesByRepo(votes, repo_id, user_id);
    updateVotesState(updatedVotes);
  }
```

**Comment by bdougie** [comment]
Yes

**Comment by hokagedemehin** [comment]
Great

will make the needed changes on the hot repositories section

**Comment by hokagedemehin** [comment]
I get this error in my chrome dev tools whenever I try to upvote any of the repos.

The numbers will increase and upon refreshing of the page, it will return back to the default

![Screenshot 2022-07-23 000757](https://user-images.githubusercontent.com/16826624/180580071-75f8e075-cd6d-427a-85fd-050d0114e73b.png)

**Comment by 0-vortex** [comment]
> I get this error in my chrome dev tools whenever I try to upvote any of the repos.
> 
> The numbers will increase and upon refreshing of the page, it will return back to the default
> 
> ![Screenshot 2022-07-23 000757](https://user-images.githubusercontent.com/16826624/180580071-75f8e075-cd6d-427a-85fd-050d0114e73b.png)

This one is for me, will check it out now!

**Comment by bdougie** [comment]
I believe this works based on the #216 merge. It did introduce this bug https://github.com/open-sauced/hot/issues/230
