### ISSUE TITLE
Bug: Make the title link to the github repo

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#22]
### Type of feature

Feature

### Current behavior

Currently the title of their repo is not clickable. 
![image](https://user-images.githubusercontent.com/5713670/146656663-ce0b8eb9-e949-4ddc-8cca-6db182127bb0.jpeg)

### Desired solution

Make the title a hyper link and link to the GitHub repository.

### Additional context

This should be a dynamic solution that is reproducible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hokagedemehin** [comment]
I will begin work on this right away. Will give feedback from time to time 😁

**Comment by jasonericdavis** [comment]
Thanks for taking this on @hokagedemehin! Please review the [CONTRIBUTING.md](https://github.com/open-sauced/.github/blob/09ed85f8482c392af87d76b356bf98f2aee1eeaa/CONTRIBUTING.md#issues) for info on how to assign yourself to the issue

**Comment by hokagedemehin** [comment]
.take
