### ISSUE TITLE
Design: Icon overlaps in mobile view

### ISSUE THREAD

**Issue by KrisMannino** [open-sauced/hot#220]
![B55B2723-D231-4AA4-B064-DF9F98DF9D0C_4_5005_c](https://user-images.githubusercontent.com/9039234/180468731-845808c4-2bab-4bd3-87ea-35aa91e741fb.jpeg)

in mobile view pizza icon overlaps the user dropdown menu

_Originally posted by @KrisMannino in https://github.com/open-sauced/hot/issues/216#issuecomment-1192670375_

**Comment by NsdHSO** [comment]
.take
