### ISSUE TITLE
Feature: Collapsible menu for Hot Cards in mobile view

### ISSUE THREAD

**Issue by KrisMannino** [open-sauced/hot#221]
### Type of feature

🍕 Feature

### Current behavior

In mobile view after selecting a menu option you have to scroll down a page and a half past the Hot Cards in order to view the associated repositories. 
![8097DC08-9A22-4B12-834F-90CA8407FAA0_1_102_o](https://user-images.githubusercontent.com/9039234/180507142-5628d9db-e55b-4011-9d2a-bf0da9b3347b.jpeg)

### Suggested solution

Implement a collapsable menu/option to collapse the Hot Cards when navigating away from the homepage when in Mobile view

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I think a simpler approach is adding a horizontal scroll. 

```css
display: inline;
overflow-y: scroll;
white-space: nowrap;
```
<img width="400" alt="Screen Shot 2022-07-30 at 9 23 42 AM" src="https://user-images.githubusercontent.com/5713670/181926150-e591abf9-170d-475f-9e40-cb8018bb1a15.png">

The tailwind classes to add [here](https://github.com/open-sauced/hot/blob/main/src/components/SecondaryNav.tsx#L39) would something like this:

```
className="space-y-2 sm:flex-row flex flex-nowrap overscroll-y-contain nowrap text-xl font-righteous text-accent font-bold justify-center items-baseline cursor-pointer"
```
This is a guess, but leverage the tailwind docs to find the solution. Also keep in mind anything with the `sm:` will reflect anything not small screens or mobile. 

https://tailwindcss.com/docs/overscroll-behavior

Do you want to try and make a contribution @KrisMannino?

**Comment by KrisMannino** [comment]
.take
