### ISSUE TITLE
Bug: data about user are printed in console 

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#222]
### Describe the bug

Data about user ar printed after logged in app 

### Steps to reproduce

1. Go to https://beta.hot.opensauced.pizza/#
2. Open console `cmd+opt+i`
3. Log in
4. You will see this things 

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Environment

Development

### Additional context

introduced in https://github.com/open-sauced/hot/pull/210

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This should be removed https://github.com/open-sauced/hot/blob/beta/src/components/PrimaryNav.tsx#L215

**Comment by NsdHSO** [comment]
.take
