### ISSUE TITLE
Bug: wrong types

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#223]
### Describe the bug

Navigation props and Supabase types are set to `any` and defined in some cases as types instead of property interfaces or defined as interfaces and not exported properly

### Steps to reproduce

1. Clone the project
2. Search the code for `eslint-disable` or `: any`

### Affected services

hot.opensauced.pizza

### Environment

Development

### Additional context

introduced in https://github.com/open-sauced/hot/pull/210

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by NsdHSO** [comment]
.take
