### ISSUE TITLE
Refactor: Replace custom hooks with rooks

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#228]
### Type of feature

🧑‍💻 Refactor

### Current behavior

We are using a custom hook for search, but @0-vortex called out the existence of this [package](https://react-hooks.org/docs/useDebounce).

https://github.com/open-sauced/hot/pull/215/files/a6d040095b2eed6863dd527596d00bebb9ceea4b#r928032778

### Suggested solution

1. Replace the [useDebounce](https://github.com/open-sauced/hot/blob/ui-v3-hero/src/hooks/useDebounce.ts) hook with [this](https://react-hooks.org/docs/useDebounce).
2. Leverage this library for this issue https://github.com/open-sauced/hot/issues/205

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hokagedemehin** [comment]
.take

**Comment by hokagedemehin** [comment]
hello @bdougie @0-vortex  👋🏽

I think I might have worked out something for this issue but want to be sure which branch you want me to make my PR to 🧍🏽‍♂️

main or beta ❔❔

**Comment by bdougie** [comment]
I would do this on beta since that has a number of upcoming updates.
