### ISSUE TITLE
Feature: Check if the user has voted on the repo

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#230]
### Type of feature

🍕 Feature

### Current behavior

This https://github.com/open-sauced/hot/pull/216 introduces the new UI to show if the user has voted. Currently the app does not have a function to check votes based on repo and user id. 

### Suggested solution

Create a function that checks the API if the user has already voted on the repo on load. this will eventually need to be cached in a global state store to prevent multiple checks on refresh or pagination. 

### Additional context
![Screen Shot 2022-07-25 at 9 02 41 AM](https://user-images.githubusercontent.com/5713670/180824020-8655b6fa-e3ad-4d10-9532-8a2b035d84c1.png)

Note the vote button states "voted." This interaction is not possible to check with this new function.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
It is possible to do this by filtering the `myVotes` array and checking if the 3 hot repo ids exist inside your repo votes

**Comment by bdougie** [comment]
> It is possible to do this by filtering the myVotes array and checking if the 3 hot repo ids exist inside your repo votes

This is a great approach.
