### ISSUE TITLE
bug: My Votes appears as an non-clickable link in the nav. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#236]
![028580BF-664C-4B63-BE24-45D5173AC749_4_5005_c](https://user-images.githubusercontent.com/9039234/180482402-274c25d4-3da0-4da9-8398-efd60469b876.jpeg)

after signing in an unlinked "My Votes" text appears next to the title, disappears after log-out (N/A in mobile)

_Originally posted by @KrisMannino in https://github.com/open-sauced/hot/issues/215#issuecomment-1192741611_

## Solution

Delete this code https://github.com/open-sauced/hot/blob/main/src/components/PrimaryNav.tsx#L83-L97

**Comment by thomasmcg77** [comment]
.take
