### ISSUE TITLE
Bug: Submit button z-index does is below the hot repos.  

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#237]
### Describe the bug

<img width="394" alt="Screen Shot 2022-07-26 at 8 39 59 PM" src="https://user-images.githubusercontent.com/5713670/181155890-36cb0dbb-1a22-4b49-8722-225b20eab65b.png">
<img width="387" alt="Screen Shot 2022-07-26 at 8 39 47 PM" src="https://user-images.githubusercontent.com/5713670/181155902-b0862dc6-1520-4aae-a3e7-2e77a9dc7bf7.png">

The easy solution is add z-index, but I am not confident that is the best solution. 

### Steps to reproduce

When viewing the submission form and scrolling up into the Hot Repos section, the form is hidden.

1. Click login
2. Open the submit a repo form (bottom right after logging in)
3. scroll up 

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Ryankolsen** [comment]
.take 

..if you don't mind, I'll try it! if I can't figure a better way I'll do the z-index.
