### ISSUE TITLE
Bug: Fonts are not loading properly

### ISSUE THREAD

**Issue by pixelsbyeryc** [open-sauced/hot#243]
### Describe the bug

The fonts are not loading for me, here's the error:

```
GET https://fonts.googleapis.com/css2?family=Inter:100,200,300,400,500,600,700,800,900&family=Lexend:100,200,300,400,500,600,700,800,900&display=swap net::ERR_ABORTED 400
```

**How it looks:**

![Screen Shot 2022-07-27 at 11 51 19 AM](https://user-images.githubusercontent.com/101464991/181278695-ccea1405-9a8f-4305-bc73-da41d30ea1e2.png)

**How it should look:**

![Screen Shot 2022-07-27 at 11 54 41 AM](https://user-images.githubusercontent.com/101464991/181279484-bbb3b64c-a4d5-4a36-b9cf-c57d6b0036c3.png)

### Steps to reproduce

Just open the page on your computer, and if you have neither of the fonts installed, you'll likely get the system font.

### Affected services

hot.opensauced.pizza

### Platforms

Desktop, Mobile

### Browsers

Chrome, Safari, Other (add additional context)

### Environment

Production

### Additional context

Brave, Arc Browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
I noticed these console issues when bundling, however the font settings were implemented in another PR - will read on tailwind and google fonts preloading, hopefully I can support getting this fixed quickly! 🍕

**Comment by sadiejay** [comment]
.take

**Comment by sadiejay** [comment]
Hi! I'm not sure where to start to tackle this one, but I'll poke around in my fork and see what happens!

**Comment by pixelsbyeryc** [comment]
@sadiejay Here are more instructions from my devtools:

> The resource https://fonts.googleapis.com/css2?family=Inter:100,200,300,400,500,600,700,800,900&family=Lexend:100,200,300,400,500,600,700,800,900&display=swap was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

Maybe that will help guide you 🙏

**Comment by 0-vortex** [comment]
[In the `vite.](https://github.com/open-sauced/hot/blob/a0f1162af9873f2d39863ce180d039fc6caabede/vite.config.ts#L68)

This line should be `Lexend`, that will fix the hero fonts

**Comment by 0-vortex** [comment]
> https://github.com/open-sauced/hot/blob/a0f1162af9873f2d39863ce180d039fc6caabede/vite.config.ts#L68
> 
> This line should be `Lexend`, that will fix the hero fonts

Scratch that, the correct fix is this:

```
'Inter:wght@100,200,300,400,500,600,700,800,900',
'Lexend:wght@100,200,300,400,500,600,700,800,900'
```

It was missing `wght@` keyword ... my bad 🍕
