### ISSUE TITLE
Bug: Featured cards are missing styles from the design

### ISSUE THREAD

**Issue by pixelsbyeryc** [open-sauced/hot#244]
### Describe the bug

There are some contrast/legibility issues with the current layout. Some of the text is very small, and doesn't have a good `font-weight` to compensate. Some are calling too much attention for not having a subtler color.

#### Here are the differences in style:
- [x] Outer `border-radius` is `8px`. **Should be `16px`, or `1rem`.**
- [x] Organization name: 
  - [x] `font-size` is `.75rem`, or `12px`. **Should be `.875rem` (or `14px`).**
  - [x] `font-weight` is not set. **Should be `medium` (or `500`).**
- [x] Upvote button: 
  - [x] Color is black for the text, border, and icon. **Should be shades of gray.**
  - [x] **Background should be the lightest gray shade**, instead of white.
  - [x] #230 
- [x] Description text: has a `400` (regular) font-weight. **It should be `500`.**
- [ ] Data items (issues, stars, PRs, and contributors):
  - [x] `font-size` is `0.75rem` (`12px`). **Should be `0.875rem` (or `14px`).** It'll improve the legibility
  - [x] Color is black. **Should be shades of gray for the text and icon.**
  - [x] Icon sizes are set in `1em`. That means it'll be equal to 1 times the size of the parent `font-size`. In this case, it's `12px`. **It should be `1rem`, so it's based on the root `font-size`, which is `16px`.**
  - [ ] #286

**How it should look:**
<img width="770" alt="Screen Shot 2022-07-27 at 12 04 41 PM" src="https://user-images.githubusercontent.com/101464991/181281852-824d0969-9a22-4fcd-89e4-e4ab3b6a1d4d.png">

**How it currently looks:**
<img width="690" alt="Screen Shot 2022-07-27 at 12 04 14 PM" src="https://user-images.githubusercontent.com/101464991/181281720-0b6dd40a-d505-484a-b626-cd24c2d1e71b.png">

### Steps to reproduce

[You can pick the CSS from Figma here.](https://www.figma.com/file/z0LEHrTwmvuCokhbYmIhPd/OpenSauced-%E2%80%94-Hot-(hot.opensauced.pizza)?node-id=3%3A2)

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by shapaaa** [comment]
Hi @pixelsbyeryc 
Can I take this issue?

**Comment by pixelsbyeryc** [comment]
> Hi @pixelsbyeryc Can I take this issue?

Hey @shapaaa! Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by bdougie** [comment]
@pixelsbyeryc I don't think the figma viewable for folks outside of open sauced. Can you double check.

**Comment by pixelsbyeryc** [comment]
I made it public @bdougie @shapaaa! ✌️

**Comment by shapaaa** [comment]
.take
