### ISSUE TITLE
Feature: title in the card should link to app.opensauced.pizza

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#245]
### Type of feature

🍕 Feature

### Current behavior

When viewing the card, nothing is linked. The expectation is that title should link to the app. 

i.e. app.opensauced.pizza/repos/${data.full_name} 

### Suggested solution

The [mocked data](https://github.com/open-sauced/hot/blob/main/src/components/HotRepositories.tsx#L18) is incorrect and should provide the repo full name too. The full name is the combo of user and repo name, i.e. open-sauced/hot or `${organization}/{name}`

cc / @hokagedemehin 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hokagedemehin** [comment]
.take
