### ISSUE TITLE
Bug: Popular text is not aligned

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#251]
### Describe the bug

![Screen Shot 2022-07-27 at 3 12 36 PM](https://user-images.githubusercontent.com/5713670/181381704-9e49b378-c10d-4f93-992d-0f79933e0dc9.png)

shout to Bajosi

### Steps to reproduce

Please to fix

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Ryankolsen** [comment]
.take

**Comment by AlexBurneikis** [comment]
The reason that this is occurring is because space-y-2 applies space between elements in the flex row so it tries to put it above only the elements that have something above them. This can be fixed by removing the space-y-2 and applying a spacing in another fashion. Fix coming soon!

**Comment by bdougie** [comment]
closed on #253
