### ISSUE TITLE
Bug: list display shows wrong results on initial load

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#255]
### Describe the bug

Refreshing the page on any of the URLs doesn't filter the initial repository list display, defaulting to most popular repos instead of the route `activeLink` 

### Steps to reproduce

1. Visit https://hot.opensauced.pizza/myVotes
2. You see the most popular repositories instead of your own votes

### Affected services

hot.opensauced.pizza

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hokagedemehin** [comment]
.take
