### ISSUE TITLE
Feature: Missing login flow that disrupts the voting logic

### ISSUE THREAD

**Issue by hokagedemehin** [open-sauced/hot#257]
### Type of feature

🍕 Feature

### Current behavior

when you log in at [https://hot.opensauced.pizza/](https://hot.opensauced.pizza/) using your Github, everything should work fine except the voting logic.

If you tried to upvote any of the repo, the number will increase but the information is not sent to the database. Below screenshot is the error you will get in your console
![Screenshot 2022-07-23 000757](https://user-images.githubusercontent.com/16826624/181579281-e289ff9d-63a0-4fff-90cf-74a27ce1a9a6.png)

The only way to address this issue is to install open sauced in your GitHub and that workflow is only possible when you log in via  [https://opensauced.pizza/](https://opensauced.pizza/) which is not stated anywhere in the site and also which is a long journey

### Suggested solution

Change the way users login in [https://hot.opensauced.pizza/](https://hot.opensauced.pizza/) and either add the necessary steps to install open sauced or create a new concept that will make the voting logic work for any user here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Great catch, that is indeed the reason it doesn't work by simply logging in and voting - having gone through the app.opensauced.pizza flow we have an installation id and explicit consent to backfill some public data available via the github api.

The correct long term fix would be to enroll users on login with "hasOpenSaucedInstalled: false", giving everyone the ability to vote - this will likely happen through the upcoming API.

As a temporary fix to this issue, "supabase.ts" could be enhanced with an "userHasOpenSaucedInsed" function that checks the supabaseAuth.user id against our existing users table to return a boolean indicating whether the user should login to app.opensauced.pizza if we don't have the user in our database. this can be done through a top level notification, auto firing modal, etc - but it is the quickest way to get around the issue and we can incrementally improve it later on!

**Comment by bdougie** [comment]
Discovered more broken use cases with voting via the new API - https://beta.api.opensauced.pizza/docs#/Vote%20service/voteOneById
