### ISSUE TITLE
Bug: incorrect search box z-index

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#259]
### Describe the bug

Search box results z-index is below the hot repositories

### Steps to reproduce

1. Go to https://hot.opensauced.pizza
2. Search for any repository
3. See the avatars stomp the search box: 

<img width="455" alt="Screenshot 2022-07-29 at 10 35 47" src="https://user-images.githubusercontent.com/237133/181719448-3f82704a-fde4-4ac0-9f94-da1e86f77e9e.png">

### Affected services

hot.opensauced.pizza

### Environment

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by NsdHSO** [comment]
.take

**Comment by NsdHSO** [comment]
@0-vortex  I think z-index is good, but I give him a shadow, to make little bit differences about hot repo. I need opinion from @pixelsbyeryc  If this looks good, I can did PR.

**Comment by 0-vortex** [comment]
> @0-vortex  I think z-index is good, but I give him a shadow, to make little bit differences about hot repo. I need opinion from @pixelsbyeryc  If this looks good, I can did PR.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/37635083/182308981-6e179daa-0208-42ce-a43a-d64af899c5ff.png)
> 
> 

There are 20+ tickets open, can you please pick up one of the existing issues rather than scope creep on design?

We have actual bugs that need fixing, many and small. You cannot define global patterns for shadows so implementing them as part of 1 component is just way of creating inconsistent design.

Also this would count the 3rd time somebody starts to figure out the zIndex issue just to leave bugged and do something else in the process 🤔

**Comment by bdougie** [comment]
I think the z-index thing was already solved here when the contributors were fixed in the hotrepositories component in this PR https://github.com/open-sauced/hot/pull/242

To be fair, the shadow is needed since the search box blend awfully with the next section. I brought him up on stream on Friday. But to @0-vortex point, this is indeed some scope creeping on the original focus of the bug. Please open a separate issue for this shadow work.
