### ISSUE TITLE
Feature: Make Jest work with this project. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#26]
### Type of feature

Test

### Current behavior

There is now one test included in this project. It will not run using Vite. From my research, this is possible with the inclusion of Babel. 

https://github.com/open-sauced/hot/pull/25

### Desired solution

Make `npm t` work

https://github.com/open-sauced/hot/blob/main/src/lib/humanizeNumber.test.js

### Additional context

https://vitest.dev/ is another solution, but currently in alpha

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
[Jest can do ESM](https://jestjs.io/docs/ecmascript-modules) - how do you feel about using jest like that with astro?

**Comment by 0-vortex** [comment]
> [Jest can do ESM](https://jestjs.io/docs/ecmascript-modules) - how do you feel about using jest like that with astro?

Astro is actually using some Babel under the hood, might just look at it like that first!

**Comment by 0-vortex** [comment]
.take
