### ISSUE TITLE
Bug: correct global z-index fix

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#262]
### Describe the bug

Z-index needs to be applied to positioned top-level containers in the order of overlap:
- header: 3
- content: 2
- footer: 1

Some of the items that exist, that are positioned inside the above containers, like the avatar image, need to also be fine-tuned when hard-coding them wasn't needed.

### Steps to reproduce

1. Go to https://hot.opensauced.pizza
2. Hover over the middle hot repo
3. It should overlap the content and look like this:

<img width="477" alt="Screenshot 2022-07-29 at 16 19 04" src="https://user-images.githubusercontent.com/237133/181780971-4e66576f-e426-4db9-a9f9-725725ab44d9.png">

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
A lot of these elements conflicting with the z-index have been removed in the new design. We may be good on this, and can potentially close it.

**Comment by 0-vortex** [comment]
> A lot of these elements conflicting with the z-index have been removed in the new design. We may be good on this, and can potentially close it.

Agreed, if we run into future z-index requirements, the above pattern should be kept, having z-index on the top-most container elements so the children components can successfully overlap markup that is outside of the container viewport! 🍕 🚀
