### ISSUE TITLE
Bug: IMHO, I think the nav should have a certain max width and not always expand out based on the screen size.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#263]
> IMHO, I think the nav should have a certain max width and not always expand out based on the screen size.
> 
> The same way the rest of the page has a max width it can expand to

@NsdHSO I agree with @hokagedemehin... Having a `max-width` will contain the contents, and help it look good on bigger screens. Our eyes scan from side to side, so imagine on a ultra-wide 49" monitor how it'd be to scan across.

But as @bdougie, we can move on and open another issue specifically for this. 🙌 

**Suggested `max-width`:** 1024px, 1280px, or 1440px... It could even be a combination of these, that would increase as the screen size gets bigger, eg:
- Viewport width > 1200px 👉  `max-width: 1024px`
- Viewport width > 1400px 👉  `max-width: 1280px`
- Viewport width > 1600px 👉  `max-width: 1440px`

_Originally posted by @pixelsbyeryc in https://github.com/open-sauced/hot/issues/260#issuecomment-1199744814_

**Comment by bdougie** [comment]
@NsdHSO if you are interested, feel free to grab.

**Comment by bdougie** [comment]
I think we can add the following to the [PrimaryNav className](https://github.com/open-sauced/hot/blob/main/src/components/PrimaryNav.tsx#L15) and call it a day. Test it out though. 
```
className="max-w-screen-xl mx-auto"
```

This is how @hokagedemehin did it [in the HotRepositories](https://github.com/open-sauced/hot/blob/main/src/components/HotRepositories.tsx#L69) and I think it is a good approach.

**Comment by hokagedemehin** [comment]
.take

**Comment by CMCSWEENE** [comment]
.take
