### ISSUE TITLE
Feature: Add contributors to the search results

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#265]
### Type of feature

🍕 Feature

### Current behavior

Currently:
<img width="604" alt="Screen Shot 2022-07-30 at 3 00 00 AM" src="https://user-images.githubusercontent.com/5713670/181905395-bd4310a9-5d37-4382-8d99-f03f7a657f2a.png">

Before:
<img width="640" alt="Screen Shot 2022-07-30 at 3 02 20 AM" src="https://user-images.githubusercontent.com/5713670/181905436-bf7d5b93-a4c5-41de-babb-388c52f517b6.png">

This, unfortunately, was not documented at the time, in the future if issues occur please open an issue and document. @shamimbinnur mention that the array was returning an empty array in his PR https://github.com/open-sauced/hot/pull/215/files#r927982011

<img width="791" alt="Screen Shot 2022-07-30 at 3 05 49 AM" src="https://user-images.githubusercontent.com/5713670/181905533-8535dc54-ea8c-432d-9641-4ad1d534599a.png">

### Suggested solution

Add this code back [here](https://github.com/open-sauced/hot/blob/main/src/components/Hero.tsx#L82). 

```
{result.contributions.map((contribution) => (
  <div className="flex items-center overflow-hidden rounded-full w-8 h-8">
     <Avatar contributor={contribution.contributor} lastPr={contribution.last_merged_at} />
  </div>
))}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ddsuhaimi** [comment]
.take

**Comment by ddsuhaimi** [comment]
@bdougie how many avatar at max can be displayed? 3? Is this OK?
![image](https://user-images.githubusercontent.com/30659198/182284231-c7b95651-f4a7-4a92-8daf-67cee074eb9a.png)
