### ISSUE TITLE
style fix: Making the gradient text classes more intuitive would be nice:

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#266]
Making the gradient text classes more intuitive would be nice:
- `headerTextGradientStart/headerTextGradientMiddle/headerTextGradientEnd` - 👎 
- `headerTextGradient0/headerTextGradient50/headerTextGradient100` - 👍 

However, this is the wrong approach as we do not have the colors available as (actually) re-usable classes, we should create the gradient based on existing theme colors, rather than create duplicate color classes subsets for the gradients. 

Visually, our start, middle and end color colors are not perceived by our users, it is unlikely the end and start color stops need additional hex colors other than the ones we have. I'm keen to stop introducing unwanted things we then have to open new fix PRs for.

_Originally posted by @0-vortex in https://github.com/open-sauced/hot/pull/242#discussion_r933760318_

**Comment by rohit1101** [comment]
Can I work on this @bdougie ?

**Comment by nickytonline** [comment]
I'm currently discussing colour/typography etc. with @isabensusan in general, although we're more focused on the app atm, and not the hot repo.

**Comment by rohit1101** [comment]
@nickytonline @bdougie  Ok where can I find active issues to contribute ?

**Comment by nickytonline** [comment]
When ininitially responded to this, I thought it was for the app repo. I edited my comment to reflect that.

This issue is a year old, so I don't really have much context on it.

For contributing @rohit1101, check out the [contributing guide](https://github.com/open-sauced/hot#-contributing).
