### ISSUE TITLE
Feature: Remove tailwinds anti-pattern 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#267]
### Type of feature

🧑‍💻 Refactor

### Current behavior

Through out the app we are using hard-coded px 
```
 <div className="mx-auto max-w-7xl px-[16px] mt-[40px]">
```

### Suggested solution

We need to use the design system provided by Tailwind or provide variables. 

```
 <div className="mx-auto max-w-7xl px-2 mt-4">
```

### Additional context

Please work on each file independently. Do not open a PR for all files, but one file per PR to avoid merge conflicts.

- [x] #314
- [x] #315
- [x] #316
- [x] #317
- [x] #318

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Fonts were switch in the PostList in this PR #242

**Comment by shamimbinnur** [comment]
Going to take this over.

**Comment by shamimbinnur** [comment]
@bdougie As, it's the changes for the whole project, what do you about breaking these issues into separate issues and PR?

**Comment by 0-vortex** [comment]
> @bdougie As, it's the changes for the whole project, what do you about breaking these issues into separate issues and PR?

A lot of this is done in #269 - if you wait for that to get merged in this ticket doesn't need to be broken up into smaller pieces, just search and replace! 🍕

**Comment by shamimbinnur** [comment]
@0-vortex  what's the best thing I can do right now?

**Comment by 0-vortex** [comment]
> @0-vortex what's the best thing I can do right now?

You can start working on this from the `beta` branch, #269 has been merged in! 🍕 🚀
