### ISSUE TITLE
Feature: Suspense or SWR? Anticipate loading content

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#270]
### Type of feature

🔥 Performance

### Current behavior

When loading from the API the screen presents empty space. Ideally, we would provide a loading component but I also think adding something SWR would make sense. We are doing both in app.opensauced.pizza - [LINK to that](https://github.com/open-sauced/open-sauced/blob/93654fb65801283385cc423a3e04caced0353db0/src/lib/hooks.js)

Open to suggestions too.

## Loading
<img width="1840" alt="Screen Shot 2022-07-30 at 10 29 40 AM" src="https://user-images.githubusercontent.com/5713670/181935077-4870da76-2521-4c98-82aa-a74d4307385d.png">

## Loaded
<img width="1840" alt="Screen Shot 2022-07-30 at 10 29 43 AM" src="https://user-images.githubusercontent.com/5713670/181935177-0008faad-bd82-46f4-9e4b-1f9b0c0f2a0d.png">

### Suggested solution

1. Implement [SWR](https://swr.vercel.app/)
2. Bonus, implement global state for storing repositories. This would assist in repainting the screen on refresh despite the data not changing.

### Additional context

https://github.com/open-sauced/open-sauced/blob/93654fb65801283385cc423a3e04caced0353db0/src/lib/hooks.js

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
`.take`
