### ISSUE TITLE
Bug: dedupe handleVoteUpdateByRepo function

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#271]
### Describe the bug

Any part of the website that can be used to vote requires posthog and as such the `handleVoteUpdateByRepo` function should be deduplicated and moved to the lib folder.

### Steps to reproduce

Duplicated code exists in:
- [ ] `PostList.tsx`
- [ ] `PostGrid.tsx`
- [ ] `HotRepositories.tsx`

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by SunGoldTech** [comment]
.take

**Comment by SunGoldTech** [comment]
having errors related to line breaks after pulling updates from the main repo...
![Screenshot (17)](https://user-images.githubusercontent.com/62995161/182801580-995686f3-a820-4d2d-974c-b0bb422199c9.png)

Can any propose a fix to this? would appreciate

**Comment by 0-vortex** [comment]
> having errors related to line breaks after pulling updates from the main repo...
> 
> ![Screenshot (17)](https://user-images.githubusercontent.com/62995161/182801580-995686f3-a820-4d2d-974c-b0bb422199c9.png)
> 
> 
> 
> Can any one propose a fix to this? would appreciate

`npm run format` should fix the issur - it's complaining about line endings (which are windows atm). When commiting, git sets them to LF (unix).

This should be a better way to fix it: https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows

**Comment by SunGoldTech** [comment]
> > having errors related to line breaks after pulling updates from the main repo...
> > ![Screenshot (17)](https://user-images.githubusercontent.com/62995161/182801580-995686f3-a820-4d2d-974c-b0bb422199c9.png)
> > Can any one propose a fix to this? would appreciate
> 
> `npm run format` should fix the issur - it's complaining about line endings (which are windows atm). When commiting, git sets them to LF (unix).
> 
> This should be a better way to fix it: https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows

Thanks @0-vortex, you the boss :)
