### ISSUE TITLE
Bug: my votes array needs global caching and display feedback

### ISSUE THREAD

**Issue by CMCSWEENE** [open-sauced/hot#272]
### Describe the bug

once signed in with get up, clicking on the upvote button cause page to glitch. After pressing upvote multiple time it works and changes from upvote to vote.

### Steps to reproduce

1. Go to https://hot.opensauced.pizza
2. Vote on a repository that doesn't exist in https://hot.opensauced.pizza/myVotes
3. Refresh page
4. Vote on the previously voted repository that doesn't indicate you vote

### Affected services

hot.opensauced.pizza

### Platforms

All

### Browsers

All

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Thanks for catching this, my votes array needs to be cached somehow, either globally or as a hook, it is currently being digested inside `HotRepositories.tsx`. The `voted` icon should also reflect whether a user has voted or not, to remove the possibility of failure! 🍕

**Comment by 0-vortex** [comment]
`.take`
