### ISSUE TITLE
Bug: Left-most avatar get overlapped during hover

### ISSUE THREAD

**Issue by ddsuhaimi** [open-sauced/hot#279]
### Describe the bug

![image](https://user-images.githubusercontent.com/30659198/182437072-1625ca4f-7253-42fa-8c96-d68367675960.png)

### Steps to reproduce

1. Go to [https://hot.opensauced.pizza/](https://hot.opensauced.pizza/)
2. Hover to avatar in repository card

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@favourite1975 Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.
