### ISSUE TITLE
Feature: added system notification 

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#281]
### Type of feature

🍕 Feature

### Current behavior

We use `console.log`. 
![image](https://user-images.githubusercontent.com/37635083/182454799-36ac5fb1-a1e8-4db5-9a0c-5edcbbbfb638.png)
But we want to avoid this feature. To implement a system message to avoid `console.log`  
I wanted to reflect on visual notifications for user

### Suggested solution

Implement some toast notifications like:

- https://github.com/fkhadra/react-toastify
- https://github.com/timolins/react-hot-toast
- https://github.com/iamhosseindhv/notistack
- https://github.com/react-component/notification

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
looks like a good first issue!

**Comment by SunGoldTech** [comment]
> looks like a good first issue!

I'll work on this feature as a starting point, utilizing react-hot-toast :)

**Comment by 0-vortex** [comment]
> > looks like a good first issue!
> 
> I'll work on this feature as a starting point, utilizing react-hot-toast :)

Awesome to hear, please take a look at https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues to see how to assign this issue to yourself! 🍕

**Comment by SunGoldTech** [comment]
.take

**Comment by SunGoldTech** [comment]
> > > looks like a good first issue!
> > 
> > 
> > I'll work on this feature as a starting point, utilizing react-hot-toast :)
> 
> Awesome to hear, please take a look at https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues to see how to assign this issue to yourself! pizza

Thanks for the heads-up @0-vortex
