### ISSUE TITLE
style: Add the white border to the StackedAvatars component 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#286]
![image](https://user-images.githubusercontent.com/5713670/182715427-561eafc7-5086-4289-9f74-149e1c1c87db.png)

Code lives here:
1. https://github.com/open-sauced/hot/blob/main/src/components/HotRepositories.tsx#L126-L132
2. https://github.com/open-sauced/hot/blob/main/src/components/PostList.tsx#L69-L77
3. https://github.com/open-sauced/hot/blob/main/src/components/Hero.tsx#L108 - not implemented yet https://github.com/open-sauced/hot/issues/265

**Comment by Deselikem** [comment]
.take

**Comment by yhoungdev** [comment]
.take

**Comment by yhoungdev** [comment]
Actually fixing it, I was having some kind burn out

**Comment by yhoungdev** [comment]
I noticed that the avatar only displays on specific projects ( repositories)

**Comment by yhoungdev** [comment]
Ooh got that now . Gonna raise the PR

**Comment by bdougie** [comment]
Checking in to see where this is at @yhoungdev

**Comment by yhoungdev** [comment]
Very possible

**Comment by blackgirlbytes** [comment]
@yhoungdev Something like this could work. This is in the StackedAvatar.tsx. If you see a more optimal way to do this, feel free! But this is what I was able to do in like 5 mins. You can play around with the width thickness etc. 

<img width="995" alt="Screen Shot 2022-08-30 at 8 10 37 PM" src="https://user-images.githubusercontent.com/22990146/187565176-d64e94eb-20d4-493d-9ae4-4500418ec7ca.png">

<img width="907" alt="Screen Shot 2022-08-30 at 8 10 49 PM" src="https://user-images.githubusercontent.com/22990146/187565195-a1aedc8d-d770-4550-a66f-5018b5671bdc.png">

**Comment by yhoungdev** [comment]
goona do that Now
