### ISSUE TITLE
Feature: Make the contributors StackedAvatars component reusable

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#287]
### Type of feature

🍕 Feature

### Current behavior

The contributor's avatar list has been built 3 times in 3 different places. Let's make this a reusable component. 

### Suggested solution

Port this code into one reusable component

https://github.com/open-sauced/hot/blob/main/src/components/HotRepositories.tsx#L126-L132
https://github.com/open-sauced/hot/blob/main/src/components/PostList.tsx#L69-L77
https://github.com/open-sauced/hot/blob/main/src/components/Hero.tsx#L108 - not implemented yet https://github.com/open-sauced/hot/issues/265

### Additional context

related https://github.com/open-sauced/hot/issues/286

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by SunGoldTech** [comment]
.take
