### ISSUE TITLE
Style: Tailwind Config Variables

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#288]
### Type of feature

🎨 Style

### Current behavior

This project has a lot of inconsistency with variables in tailwind. We need to first clean up all the hardcode stuff https://github.com/open-sauced/hot/issues/275

Second we can address the variable naming for slate and other colors. https://github.com/open-sauced/hot/pull/274#discussion_r934733469,

### Suggested solution

The Tailwind pattern is to use numerical values for shade and opacity. That is preferred over the "light" and "lighter" stuff. 

```
grey-100
grey-200
etc
```

Be sure to be consistent and fix everywhere.  

https://github.com/open-sauced/hot/blob/main/tailwind.config.cjs#L12-L30

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by sadiejay** [comment]
.take
