### ISSUE TITLE
Feature: Add link to star the project repo

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#289]
### Type of feature

🍕 Feature

### Current behavior

When folks navigate to the hot.opensauced.pizza site, folks don't have the option to start the repo. It would be nice to include that. 

### Suggested solution

Add this to the Nav (white text on gradient background)
![Screen Shot 2022-08-03 at 3 26 48 PM](https://user-images.githubusercontent.com/5713670/182723758-ae4b57b2-e5e2-488c-829e-5a2abe491949.png)

Use the [AiOutlineStar](https://react-icons.github.io/react-icons/search?q=star) from react-icons

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This addition should link to the github repo

**Comment by AlexVCS** [comment]
Hey there, I’d like to work on this issue. Can you assign it to me please?

**Comment by 0-vortex** [comment]
> Hey there, I’d like to work on this issue. Can you assign it to me please?

Awesome to hear, please take a look at https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues to see how to assign this issue to yourself! 🍕

**Comment by AlexVCS** [comment]
.take

**Comment by yhoungdev** [comment]
.take

**Comment by bdougie** [comment]
> Add this to the Nav (white text on gradient background)
Hey @AlexVCS. Apologize, I wrote this issue while on stream. The should be `text-osGrey` and not white.
