### ISSUE TITLE
Feature: Title in the menu needs to be in OpenSans font

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#295]
### Type of feature

🐛 Fix

### Current behavior

<img width="176" alt="Screen Shot 2022-08-06 at 10 09 25 AM" src="https://user-images.githubusercontent.com/5713670/183259037-737556c9-5ec2-49d6-be30-4b14873769af.png">
 
The open sauced landing page has the correct font. 

<img width="484" alt="Screen Shot 2022-08-06 at 10 23 37 AM" src="https://user-images.githubusercontent.com/5713670/183259423-297a0bab-0c89-49c6-b4cf-43537c73a56f.png">

https://github.com/open-sauced/landing-page/blob/main/tailwind.config.js#L39

### Suggested solution

1. Install [Open Sans](https://fonts.google.com/specimen/Open+Sans?subset=cyrillic&sort=alpha) font (weight 400) in the [tailwind.config](https://github.com/open-sauced/hot/blob/main/tailwind.config.cjs#L38-L41).
2. Update the font family for the title. here: https://github.com/open-sauced/hot/blob/main/src/components/PrimaryNav.tsx#L25
3. Kerning between letters is -6% (in figma) not sure how that translate in CSS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dinnyscript** [comment]
.take

**Comment by erum-hassan** [comment]
Is it still open i want to take it.

**Comment by ddsuhaimi** [comment]
> Is it still open i want to take it.

@dinnyscript already took it

**Comment by Shoetan** [comment]
Hi everyone. is this issue still open ?? Would love to take it.

**Comment by ddsuhaimi** [comment]
> Hi everyone. is this issue still open ?? Would love to take it.

Currently, it's already assigned to @dinnyscript

**Comment by Shoetan** [comment]
> > Hi everyone. is this issue still open ?? Would love to take it.
> 
> Currently, it's already assigned to @dinnyscript

ok thanks

**Comment by dinnyscript** [comment]
Hey, 
For the font kerning, I could not find a way to set a certain value for it in CSS - I think the best alternative is letter-spacing, although it is not exactly the same thing. I have used tailwind's tracking-tighter to achieve the effect. Here is the current behavior:
![image](https://user-images.githubusercontent.com/76710999/183779442-5b1eed8a-6a2d-407a-834d-21fbb96881e3.png)

Let me know if this is fine. Thanks!

**Comment by 0-vortex** [comment]
> Hey, 
> 
> For the font kerning, I could not find a way to set a certain value for it in CSS - I think the best alternative is letter-spacing, although it is not exactly the same thing. I have used tailwind's tracking-tighter to achieve the effect. Here is the current behavior:
> 
> ![image](https://user-images.githubusercontent.com/76710999/183779442-5b1eed8a-6a2d-407a-834d-21fbb96881e3.png)
> 
> 
> 
> Let me know if this is fine. Thanks!

Do you have a PR for that? Also, kerning would be set from the font weight additional options we are loading from google fonts (that would be in the vite.config.ts file)

**Comment by dinnyscript** [comment]
I just created a PR for the issue. For the font kerning, I checked the vite.config.ts file although I am still unsure on how to continue. Any help would be appreciated.

**Comment by bdougie** [comment]
Did you take a look at the landing-page repo. All of the above is achieved there.

**Comment by dinnyscript** [comment]
It seems the landing-page repo uses a .svg file for the logo?

**Comment by bdougie** [comment]
Ah that makes sense. Perhaps we do that instead, sorry for the runaround on this.

**Comment by 0-vortex** [comment]
Looking at Figma font pairings, that is clearly not 16px normal weight: https://www.figma.com/file/OWzJRZoB7I2KXCppuzuq0v7E/Open-Sans-Pairings/duplicate?node-id=0%3A1

We should add `600` or `900` weight and potentially make it bigger even. At 16 pixels bold it might still be skinnier than in the OP screenshot but it should do the trick and look good in the preview! 🍕 

That should fix the font, from a technical perspective, it doesn't make sense to wrap the text around in an SVG image as that would just be markup with better CSS, we should add some classes, drop shadows, transitions, etc on the element itself with tailwind utilities.

**Comment by dinnyscript** [comment]
Here is the title with 900 weight and tracking-tighter:
![image](https://user-images.githubusercontent.com/76710999/184020257-924482ec-5079-4df3-90dd-edf8fcfb23ac.png)

Does this look ok?

**Comment by 0-vortex** [comment]
> Here is the title with 900 weight and tracking-tighter: ![image](https://user-images.githubusercontent.com/76710999/184020257-924482ec-5079-4df3-90dd-edf8fcfb23ac.png)
> 
> Does this look ok? It is definitely not as bold as the OP screenshot however

Amazing! I like it, you can also try with `text-xl` (20px) and see if that is better! 🍕 Go with your gut feeling IMHO

**Comment by dinnyscript** [comment]
Got it, I will try some different text sizes and then set the PR for review. Thanks!
