### ISSUE TITLE
Feature: Tooltip for Avatars

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#30]
### Type of feature

Feature

### Current behavior

Each card has a list of contributors with no context of who they are. I would love to add a tooltip on wh

![Group 2](https://user-images.githubusercontent.com/5713670/147105019-102711a7-335e-4985-9980-d730540a089f.png)

similar to https://github.com/open-sauced/hot/issues/21

### Desired solution

This may be accomplished through a [react tooltip](https://www.npmjs.com/package/react-tooltip) library or similar. 

1. Add a tooltip on hover
2. Ensure the [cursor-pointer](https://github.com/open-sauced/hot/blob/732680ea21028f593f3c7c35e733b5cdbece70fd/src/components/SecondaryNav.astro#L5) is added with Tailwind 

![tooltip](https://user-images.githubusercontent.com/5713670/147105177-8adb8cf3-d511-4f10-ae8d-3918b1e42147.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelvinsekx** [comment]
.take

**Comment by kelvinsekx** [comment]
.take

**Comment by bdougie** [comment]
@kelvinsekx let me know if you have any questions on this.

**Comment by kelvinsekx** [comment]
Sure I will.
I'm particularly new to tailwind...so I will reach out if there be need. 

I would work on all issues assigned to me today.

**Comment by kelvinsekx** [comment]
I think you disabled the eslint in the last merge.
Really struggling with eslint troubles.

**Comment by 0-vortex** [comment]
> I think you disabled the eslint in the last merge. Really struggling with eslint troubles.

Disable any editor integrations and run it using `npm run lint` and `npm run format` please

**Comment by kelvinsekx** [comment]
Hoo okay. I will do that and send back the feedback
