### ISSUE TITLE
Feature: Add submit a repo to the nav

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#301]
### Type of feature

🍕 Feature

### Current behavior

Folks are frankly not submitting repos as much as I thought. We will start introducing some features to make this more prominent on the page, but for now let's add the link to the nav menu.

## mock:
<img width="462" alt="Screen Shot 2022-08-10 at 9 15 59 AM" src="https://user-images.githubusercontent.com/5713670/183962740-196393a7-d193-43c0-91cb-fdd973a18c94.png">

### Suggested solution

1. Add a new menu item to the dropdown. [here](https://github.com/open-sauced/hot/blob/main/src/components/PrimaryNav.tsx#L92)
2. Move [setIsSubmissionInProcess](https://github.com/open-sauced/hot/blob/main/src/components/RepoSubmission.tsx#L14) state to context
3. 
![Screen Shot 2022-08-10 at 9 31 58 AM](https://user-images.githubusercontent.com/5713670/183964223-4e35a86c-ed63-4589-bbcf-1b6cb89a4119.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Hi there, can I work on this?

**Comment by TAKANOME-DEV** [comment]
.take

**Comment by TAKANOME-DEV** [comment]
@bdougie Can you please explain to me why do you want to move [setIsSubmissionInProcess](https://github.com/open-sauced/hot/blob/ee0af97a0f1592642f8225a80ae3ef070164a7df/src/components/RepoSubmission.tsx#L14) to context?

I did add `submit a repo` in the nav for logged in and not logged in user and everything works fine

**Comment by bdougie** [comment]
If it works without, that's great. That path was my best guess for the issue.
