### ISSUE TITLE
Bug: Load more does not refresh the page

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#302]
### Describe the bug

![Screen Shot 2022-08-10 at 9 44 10 AM](https://user-images.githubusercontent.com/5713670/183967315-2941590f-a275-4244-b6a5-5850cf157e31.png)

Seems as if the data is not re-hydrating when clicking load more. 

### Steps to reproduce

1. Open hot.opensauced.pizza
2. Scroll to the bottom
3. Click load more
4. note that the page does not add more data. 

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I am pretty sure that this [line](https://github.com/open-sauced/hot/blob/main/src/components/PostsWrap.tsx#L46) needs a `[fetchedData](https://github.com/open-sauced/hot/blob/main/src/components/PostsWrap.tsx#L31)`. Not confident, but that is what I would try first.

**Comment by ddsuhaimi** [comment]
.take
