### ISSUE TITLE
Bug: Open in application you received white screen

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#305]
### Describe the bug

Sometimes https call fails and this problem not caught.
In console received this 
![image](https://user-images.githubusercontent.com/37635083/184230091-08733d56-04a2-4350-a6eb-885bbf3c57c1.png)
In network tab received this 
![image](https://user-images.githubusercontent.com/37635083/184230309-bdf1c43a-bb82-4425-8ae2-349b0799b061.png)

### Steps to reproduce

1. Open in App 
2. Sometimes you will get white screen.

### Affected services

hot.opensauced.pizza

### Additional context

I think we will should to implemented a global Handler error 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Good catch, `.take` it I know what this is about! 🍕
