### ISSUE TITLE
Feature:  Create a "failed to load" state for the repository cards

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#307]
### Type of feature

🎨 Style

### Current behavior

If we don't find some resources we showed this
![image](https://user-images.githubusercontent.com/37635083/184239383-94ec88c9-505c-470f-bc74-a73c83e3f7e1.png)

### Suggested solution

Just an example 
![image](https://user-images.githubusercontent.com/37635083/184241047-5f65829e-0936-4766-8892-f3d66c93e41f.png)

but you can put your imagination to work for you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
If we make the "not found" error clickable, it should open an issue here saying "X repo could not be loaded" - the top 3 should normally load 😅 🍕

**Comment by NsdHSO** [comment]
@pixelsbyeryc we need your wisdom

**Comment by pixelsbyeryc** [comment]
> If we make the "not found" error clickable, it should open an issue here saying "X repo could not be loaded" - the top 3 should normally load 😅 🍕

@NsdHSO I would just add a ⚠️ or ℹ️  icon (not emojis, actual icons) by the side of the text  that says "X repo could not be loaded", and a link to open a new issue (that opens in a new tab), like @0-vortex suggested.

**Comment by NsdHSO** [comment]
.take
