### ISSUE TITLE
Feature: Need to add CI as part of the development.yml

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#31]
### Type of feature

CI

### Current behavior

Jest test now work thanks to #27, but they are not run during the CI

### Desired solution

Add the CI from open sauced here.

### Additional context

https://github.com/open-sauced/open-sauced/blob/main/.github/workflows/development.yml#L13-L32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
.take
