### ISSUE TITLE
Feature: useRef instead of querySelector in repoSubmission

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#311]
### Type of feature

🧑‍💻 Refactor

### Current behavior

Noticed in #310 that we are using a query selector in the RepoSubmission. We shouldn't do that.

https://github.com/open-sauced/hot/blob/beta/src/components/RepoSubmission.tsx#L64

### Suggested solution

Instead useRef works better and provides an elegant React solution. 

[ref.current.focus](https://reactjs.org/docs/hooks-reference.html#useref)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ddsuhaimi** [comment]
.take

**Comment by ddsuhaimi** [comment]
@bdougie I think using [useOutsideClickRef](https://react-hooks.org/docs/useOutsideClickRef) from 'rooks' could be a better solution. Let me know what you think :)

**Comment by 0-vortex** [comment]
> @bdougie I think using [useOutsideClickRef](https://react-hooks.org/docs/useOutsideClickRef) from 'rooks' could be a better solution. Let me know what you think :)

I second this! 💯
