### ISSUE TITLE
Feature: Rename everything from Post to Repo

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#313]
### Type of feature

🧑‍💻 Refactor

### Current behavior

This project started as post submissions, but in reality they are all Repos!

### Suggested solution

Please rename PostWrap to RepoWrap, and etc. Keep in mind that this is a breaking change that should point to beta.

- [ ] Rename PostGrid to RepoGrid
- [ ] Rename PostWrap RepoWrap
- [ ] Rename PostList RepoList

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by fk00750** [comment]
Hey can you assign me this issue?

**Comment by ddsuhaimi** [comment]
> Hey can you assign me this issue?

You assign yourself actually. Read [here ](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues) on how to do it :)

**Comment by bdougie** [comment]
As @ddsuhaimi mentioned, Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by fk00750** [comment]
.take

**Comment by bdougie** [comment]
I completed this on my branch #336. Hoping someone can complete this on beta before that PR lands.
