### ISSUE TITLE
Remove tailwinds anti-pattern in Hero.tsx

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#315]
Context is on the tracking issue - https://github.com/open-sauced/hot/issues/267

This issue only needs changes to this file.

**Comment by AlexVCS** [comment]
.take

**Comment by teachjenntech** [comment]
.take

**Comment by AlexVCS** [comment]
My apologies @bdougie! I've changed the code to use Tailwind's default spacing scale instead of hardcoding rem values.
