### ISSUE TITLE
Remove tailwinds anti-pattern in RepoSubmission.tsx

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#317]
Context is on the tracking issue - https://github.com/open-sauced/hot/issues/267

This issue only needs changes to this file.

**Comment by NsdHSO** [comment]
.take

**Comment by NsdHSO** [comment]
I have some question about this ticket, What I have to do because we have some custom padding,margin. Like `15px`, `300px`, `5px`... We can use mb-[0.313rem], p-[0.938] ?  OR we can add custom properties in `tailwind.config.cjs`?

**Comment by kelvinsekx** [comment]
Replacing the pixel values with rem/em is still an anti-pattern.
m-[16px] or m-[0.23em] are both anti-patterns.
