### ISSUE TITLE
Bug: README uses Markdown within HTML

### ISSUE THREAD

**Issue by willtheorangeguy** [open-sauced/hot#325]
### Describe the bug

On the copy line of the README, there is Markdown used inside HTML for the link. This does not render correctly.

It should be either all HTML or all Markdown.

### Steps to reproduce

View the `README.md` document. 

### Affected services

hot.opensauced.pizza

### Platforms

Desktop, Mobile, Tablet

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Environment

Production, Development, Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Thanks for the issue, but will have to disagree. Please present more evidence when opening issues.

**Comment by willtheorangeguy** [comment]
Maybe it is just a problem with how my computer renders Markdown, but this is what the README looks like on my computer: 
![image](https://user-images.githubusercontent.com/18339050/186962815-4279ca9c-f1a7-4dae-af7c-7d3588d1efcf.png)
