### ISSUE TITLE
refactor: It wouldn't be clean to create a function to pass these parameters and apply DRY

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#342]
Apply DRY function to the search commands https://github.com/open-sauced/hot/blob/ec60aeb7be5ccc2451fef639731045119115fa1a/src/components/Hero.tsx#L36-L42

````
function useKey(superKey, key, target, hasFocus) {
  useKeys(
    [superKey, key],
    async (e: KeyboardEvent) => {
      if (!hasFocus) {
      } else {

      }
      // prevent browser from handling CMD/CTRL + K
      e.preventDefault();
    },
    { target: target }
  );
}

_Originally posted by @NsdHSO in https://github.com/open-sauced/hot/pull/341#discussion_r975764424_

**Comment by ddsuhaimi** [comment]
.take

**Comment by ddsuhaimi** [comment]
oh actually i am not sure how to update someone's open pr #341. Normally i change the code that is already merged in main

**Comment by 0-vortex** [comment]
> oh actually i am not sure how to update someone's open pr #341. Normally i change the code that is already merged in main

Forgot to merge, did it now tho :D
