### ISSUE TITLE
Feature: Need a social card for this site. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#35]
### Type of feature

Feature

### Current behavior

When sharing this site on social, there is no social card

### Desired solution

Set up a social card with the following image. 

![social=image](https://repository-images.githubusercontent.com/71359796/179eca00-061e-11eb-9b57-856a179db1a1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelvinsekx** [comment]
.take

**Comment by bdougie** [comment]
Note that this can be done in the HTML and does not need any dynamic rendering. https://docs.astro.build/core-concepts/layouts/index.html#composing-layouts

**Comment by bdougie** [comment]
Heads @kelvinsekx I opened a PR so I can start promoting the site on social.
