### ISSUE TITLE
Bug: Node v 18.10.0 not supported

### ISSUE THREAD

**Issue by teachjenntech** [open-sauced/hot#350]
### Describe the bug

When trying to clone /hot and create branch on windows machine, downloaded Node v 18.10.0 and received error:

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @squoosh/cli@0.7.2
npm ERR! notsup Not compatible with your version of node/npm: @squoosh/cli@0.7.2
npm ERR! notsup Required: {"node":" ^12.20.2 || ^14.13.1 || ^16.0.0 "}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v18.10.0"}
npm timing npm Completed in 2297ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jenn\AppData\Local\npm-cache\_logs\2022-10-03T17_17_37_582Z-debug-0.log
```

### Steps to reproduce

Watch VOD of stream

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
good catch, should update this to be 18! 🍕 😅

**Comment by 0-vortex** [comment]
Actually realised now it's because we are using https://squoosh.app to optimize images in development, the CLI hasn't been updated past node 16 yet 😅
