### ISSUE TITLE
Create logic to check if a user has submitted the repository (GET)

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#353]
## What is this?

When submitting a repo to the app, we will need to check if the user has submitted it. This will be needed to identify the most popular users submitting repositories. 

## What is needed

A hook is needed to fetch https://api.opensauced.pizza/#/Submit%20service/findAllUserSubmitted

At the time of creating this issue, API hooks only exist on the alpha branch. Check here for a reference https://github.com/open-sauced/hot/tree/alpha/src/hooks

In this list, add an item that says `Submissions: count`

**Comment by ikezuby2012** [comment]
.take

**Comment by ikezuby2012** [comment]
so if a user has submitted the repo should it end the logic or increase the submission count

**Comment by ikezuby2012** [comment]
Yes, i observed the API handles the submission count, my issue is writing the submission count logic, is it still necessary?

**Comment by 0-vortex** [comment]
> Yes, i observed the API handles the submission count, my issue is writing the submission count logic, is it still necessary?

No, this issue is about fetching user submissions, not submitting new repos from the UI, that is issue #352

**Comment by ikezuby2012** [comment]
> > Yes, i observed the API handles the submission count, my issue is writing the submission count logic, is it still necessary?
> 
> No, this issue is about fetching user submissions, not submitting new repos from the UI, that is issue #352

ok, thank you

**Comment by sohaibchebah** [comment]
great remark
