### ISSUE TITLE
Connect stars to API star service in the API

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#355]
## What is this?

Multiple places display stars. I am looking to empower users to stars repos from the hot UI. 

<img width="405" alt="Screen Shot 2022-10-03 at 11 08 27 PM" src="https://user-images.githubusercontent.com/5713670/193747087-3552f4a4-2f16-4b16-acde-089b699ef8bc.png">
<img width="551" alt="Screen Shot 2022-10-03 at 11 11 36 PM" src="https://user-images.githubusercontent.com/5713670/193747132-9f898066-7678-4f19-96a0-cce50752d31c.png">

## how to implement
<img width="766" alt="Screen Shot 2022-10-03 at 11 08 53 PM" src="https://user-images.githubusercontent.com/5713670/193746922-1eac13fd-4c2f-4870-a2a6-6a236ea3202b.png">

Use the API to create a **useStarRepos** similar to [useVotedRepos](https://github.com/open-sauced/hot/blob/alpha/src/hooks/useVotedRepos.ts)

**Comment by TAKANOME-DEV** [comment]
I will `.take` this one and if I implement the `useStarRepos` hook, it will be easier, I think, to make https://github.com/open-sauced/hot/issues/358 work :v:

**Comment by TAKANOME-DEV** [comment]
@0-vortex we don't have the loading skeleton #374 because of the latest changes made, I would like to suggest passing down `isLoading` to `ListRepositories.tsx` instead of not rendering it until `isLoading` is false (footer still shows up)

Want to hear your thoughts on that :raised_hands:

**Comment by TAKANOME-DEV** [comment]
This issue need to be closed as well since #387 is not needed :no_entry_sign:
