### ISSUE TITLE
Feature: Loading Skeleton needed for the RepoWrap component. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#357]
### Type of feature

🍕 Feature

### Current behavior

While data is being fetched from the API, the footer is shown and looks awkward. 

![Screen Shot 2022-10-04 at 2 52 04 PM](https://user-images.githubusercontent.com/5713670/193937160-a04673da-007f-49dd-a245-2a57f9ea2125.png)

note the footer is showing without scrolling. A skeleton will push this down. 

![Screen Shot 2022-10-04 at 2 49 52 PM](https://user-images.githubusercontent.com/5713670/193937181-a8b55f0f-b816-4c6f-9372-a532fbed04d0.png)

### Suggested solution

Adding a loading skeleton similar to what we are doing in the [HotRepoCard](https://github.com/open-sauced/hot/blob/beta/src/components/HotRepoCard.tsx#L35-L44) would be ideal.

### Additional context

We are using react-loading-skeleton, please leverage that to completed this. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
.take
