### ISSUE TITLE
Feature: User should star the repo without leaving the page. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#358]
### Type of feature

🍕 Feature

### Current behavior

When I click this star button, it takes me to github. I would like the app to know if I starred the repo or not and also be able to start from the page. 

![Screen Shot 2022-10-04 at 3 08 45 PM](https://user-images.githubusercontent.com/5713670/193939230-d02aa4fa-fa2c-4662-b0d1-81ca3161260b.png)

### Suggested solution

Connected this component to the API endpoint for stargazing

```
https://api.opensauced.pizza/v1/repos/open-sauced/hot/stargaze

``` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by SimranjitKaurMaan** [comment]
.take

**Comment by SimranjitKaurMaan** [comment]
.take

**Comment by SimranjitKaurMaan** [comment]
This issue seems to be resolved. Once the value for `userAndTokens?.providerToken` is set correctly, the #431  logic should work.
