### ISSUE TITLE
Feature: Add a favicon

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#36]
### Type of feature

Feature

### Current behavior

currently no favicon present.

<img width="183" alt="Screen Shot 2021-12-23 at 3 37 13 PM" src="https://user-images.githubusercontent.com/5713670/147289593-51643a94-9cb6-436a-9ecd-70a1156c6728.png">

### Desired solution

<img width="150" alt="Screen Shot 2021-12-23 at 3 36 57 PM" src="https://user-images.githubusercontent.com/5713670/147289572-fadd7296-5f18-4b4b-88a3-17eaf7431bfb.png">

This can be grabbed from https://github.com/open-sauced/open-sauced/blob/main/public/favicon.ico

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelvinsekx** [comment]
.take

**Comment by bdougie** [comment]
While poking around for the social card, I noticed that this file can be updated by placing the above URL in this file. 

https://github.com/open-sauced/hot/blob/main/public/favicon.ico

**Comment by hokagedemehin** [comment]
.take

**Comment by kelvinsekx** [comment]
I'm already on this and finished it on my part.
I only would write some test today or tomorrow and make a PR. 

If you don't mind, unassign your self?
