### ISSUE TITLE
Feature: New favicon

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#362]
### Type of feature

🍕 Feature

### Current behavior

We have new brand assets and we will need to update the favicon to the below link. 

https://github.com/open-sauced/assets/blob/main/Logos%20/slice-Black-Orange.png

![image](https://user-images.githubusercontent.com/5713670/194157454-73dc2ec0-1502-4fa2-b931-93172f190e7f.png)
### Suggested solution

The logo will need to be downloaded and renamed and replaced here 👉🏾[favicon.ico](https://github.com/open-sauced/hot/blob/beta/public/favicon.ico). Might also need to delete the favicon.svg

### Additional context

Assigning to @teachjenntech

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by teachjenntech** [comment]
.take

**Comment by bdougie** [comment]
should of been https://github.com/open-sauced/assets/blob/main/logos/slice-Black-Orange.png?raw=true
