### ISSUE TITLE
Bug: hot repo's development server is broken.

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/hot#365]
[Edited: Added some more info in context]

### Describe the bug

Running `npm start` will open a white blank page.

### Steps to reproduce

Install the repo and run `npm start`

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox

### Environment

Development
Alpha

### Additional context
~It's a white page in all browsers. However, in Firefox, this is what is displayed on console:~
![firefox_ujRwkA56zu](https://user-images.githubusercontent.com/52013393/194428164-a1189229-f7b0-4f38-b574-cd6a144abf7e.png)
~It doesn't include the issue, or even the signing text of open sauce in console.~

~But in Edge, this is what is displayed:~
![msedge_UvSxGmWzs6](https://user-images.githubusercontent.com/52013393/194428279-088ef36f-117e-4cdd-aba6-8acf234d6d5b.png)

~Here the issues and the open sauce text is displayed.
I am not sure if this is related to this issue or not.~

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Think I am the only one available to `.take` this on! 🍕

**Comment by Deadreyo** [comment]
Updated the context of the issue.

**Comment by 0-vortex** [comment]
> ~Updated the context of the issue.~
> Edit: turned out it was blocked by my adblocker

One at a time, `beta` is still bugged for me:

<img width="760" alt="Screenshot 2022-10-07 at 00 39 36" src="https://user-images.githubusercontent.com/237133/194431523-5daccd33-fe3c-4bbf-8924-96c03d14b2a6.png">
