### ISSUE TITLE
Bug: markdown emoji do not render in summary lists

### ISSUE THREAD

**Issue by peckjon** [open-sauced/hot#370]
### Describe the bug

Raw markdown being shown in project previews instead of emoji

![F4D5EC48-C4A0-42A2-A83E-676F9F252321](https://user-images.githubusercontent.com/5299412/194724180-6931bff7-f20d-46aa-b5a9-033f0b8fa2bb.png)

### Steps to reproduce

1. Go to hot.opensauced.pizza
2. Scroll to ossu/computer-science or another project with markdown emoji in the title 
3. See raw markdown `:mortar_board:` instead of icon 🎓 

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by SimranjitKaurMaan** [comment]
.take
