### ISSUE TITLE
Bug: Production site's repository list section, upvoting is not working. 

### ISSUE THREAD

**Issue by janie-lee-developer** [open-sauced/hot#385]
### Describe the bug

At production branch, popular repositories section's upvote is not working. We find 406 error on the console when we try to upvote at the popular repositories section. This error is found while reviewing #384  PR.
@bdougie  @0-vortex 

<img width="1423" alt="Screen Shot 2022-10-24 at 3 18 39 PM" src="https://user-images.githubusercontent.com/58411107/197610174-3695a88d-d90c-4215-9f92-8dd7515a7b51.png">

### Steps to reproduce

1. Go to production site, hot sauced.
2. Go to Popular Repositories section.
3. Click upvote on one of the popular repositories.
4. Check console to find the error message.

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
> PR https://github.com/open-sauced/hot/pull/384 is not released, so checking the production site is meaningless for review

@0-vortex, I am getting a 406 when voting on the deploy preview. @Deadreyo can vote via localhost on his branch. Filtering works on #384, so I will provide my approval for that, but perhaps we should move towards using the API for voting altogether.

**Comment by 0-vortex** [comment]
> > PR #384 is not released, so checking the production site is meaningless for review
> 
> @0-vortex, I am getting a 406 when voting on the deploy preview. @Deadreyo can vote via localhost on his branch. Filtering works on #384, so I will provide my approval for that, but perhaps we should move towards using the API for voting altogether.

That's #372 at work, mainly because I had to change all org envs to the new system: https://docs.netlify.com/netlify-labs/experimental-features/environment-variables/ 

Currently, env reflects this (left is hot, right is api link):
- [x] localhost -> dev.api
- [x] beta -> dev.api
- [x] production -> prod.api
- [ ] preview -> prod.api

Deploy preview still needs fixing :<
