### ISSUE TITLE
fix: Limit for useRepositories is hard coded and not flexible when paginating. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#388]
this is not taking a page argument, just increasing the limit. this makes it such a way that we cannot ever list more than 1000 repos while also, pulling more and more data from the backend; that is such an incremental way of pulling new data that I think it's worth pushing this beta back until everything is ready, since this is a quick fix and there are other inconsistencies 😓

_Originally posted by @0-vortex in https://github.com/open-sauced/hot/pull/382#discussion_r1000941133_

**Comment by rahulbansal3005** [comment]
I want to work on this.

**Comment by bdougie** [comment]
not sure if this is an issue. We'd need you to confirm that first. 

Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.
