### ISSUE TITLE
Bug: Star us on github button opens profile dropdown instead of redirecting to `hot` repo

### ISSUE THREAD

**Issue by SunGoldTech** [open-sauced/hot#391]
### Describe the bug

the `Star un on GitHub` button is currently triggering the menu dropdown for the user profile at the top right corner of the `PrimaryNav` component.

### Steps to reproduce

here is a video on steps to reproduce

https://www.loom.com/share/8b03f9b3a14144df8dc6074c5bbb64f2

### Affected services

hot.opensauced.pizza

### Environment

Production, Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ikezuby2012** [comment]
.take
