### ISSUE TITLE
Feature: Add end to end testing framework

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#395]
### Type of feature

✅ Test

### Current behavior

There are currently zero end to end test in this app and they are needed to start capturing some of the issues in the app. 

### Suggested solution

Can we explore the following and make a decision on the best framework moving forward?

- https://www.cypress.io/
- https://playwright.dev/
- or combination of both

Example tests to ship. 
- As a user, I should be able to log in
- As a user, I should not be able to vote with out being logged in. 

### Additional context

This issue should be only be adding the test framework and one test. Please do not add the whole test suite. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by mtfoley** [comment]
I’d give playwright a +1 for what that’s worth. I’ve done some stuff with it in my day job and I like it so far. Also I think the newer versions might have some good stuff with respect to being better with react apps (getting “testing library” style locators). https://playwright.dev/docs/release-notes#version-127
