### ISSUE TITLE
Feature: Sort latest repos by upvoted

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#399]
### Type of feature

🍕 Feature

### Current behavior

Latest repos are sorted by date, but they need to also be sorted by votes.

<img width="1332" alt="Screen Shot 2022-11-13 at 6 20 16 PM" src="https://user-images.githubusercontent.com/5713670/201561889-3449f23f-9e19-4e29-baf9-ce6d554f3a84.png">

### Suggested solution

After sorting by created_at - https://github.com/open-sauced/hot/blob/7ae4f4fd37f1ffe04627efa1b1120b683969c2aa/src/components/RecentRepoListWrap.tsx#L52

Then sort by vote count

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by ikezuby2012** [comment]
.take

**Comment by KarthikRaju391** [comment]
Hey @bdougie, I would love to work on this feature!

**Comment by Deadreyo** [comment]
> Hey @bdougie, I would love to work on this feature!

hello @KarthikRaju391 
Taking up issues is done automatically by commenting `.take` as mentioned in contributing.md. You should have a look at it

**Comment by KarthikRaju391** [comment]
Oh, ok. Thanks!
