### ISSUE TITLE
Feature: UI Component Implementation

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#4]
### Type of feature

Tailwind powered React components

### Current behavior

This project is powered by api.opensauced.pizza, a list of popular open source projects. I am looking to add React components (powered by Tailwind) to display the repos.

### Desired solution

This is the mock-up https://hot-open-sauced.vercel.app/ link to code coming soon. [Link to the repo with a working solution in Next](https://github.com/bdougie/hot-open-sauced) (note this project is Astro).

Astro provides the ability to add React components to 

- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10

### Additional context

![Screen Shot 2021-12-15 at 6 48 36 AM](https://user-images.githubusercontent.com/5713670/146208185-bc1ed918-fca9-4fb5-aeca-ae25bf13b0b7.png)
![Screen Shot 2021-12-15 at 6 48 28 AM](https://user-images.githubusercontent.com/5713670/146208192-9a41b7a9-6245-4da5-8a8e-e58874dda942.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NaaLaryea** [comment]
Hello @bdougie looked at this and i am interested

**Comment by bdougie** [comment]
Thanks for responding @NaaLaryea  Please review the [CONTIBUTING.md](https://github.com/open-sauced/open-sauced/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by bdougie** [comment]
All have been completed.
