### ISSUE TITLE
Feature: End to end testing tracking issue

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#403]
### Type of feature

✅ Test

### Current behavior

While chatting with @JoshuaKGoldberg yesterday and discussing an approach for end-to-end testing of this app. I will use this as a tracking issue for setting up end to end testing with Cypress, now that testing works, sort of - https://github.com/open-sauced/hot/pull/400. 

### Suggested solution

**Feature Testing plan**

So far, we are testing logged in/out users. The following features will also need tests for functionality with a lens on accessibility.

- [ ] #411
- [ ] #412
- [ ] #413
- [ ] #414

### Additional context

End-to-end testing is conducted through Cypress. Here is a guide - https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Currently using puppeteer but the action implementation has been lagging, tho I don't mind switching to cypress! 🍕

**Comment by 0-vortex** [comment]
> @0-vortex , @bdougie what should I use to make E2e test? puppeteer | cypress? I have this ticket #414, and I saw a ticket about accessibility. I should wait until it is finished #418?

I know you asked about this in discord as well, putting this here for reference: as per #395 we are using https://playwright.dev 🔥
