### ISSUE TITLE
Feature: Hot repositories needs to be dynamically updated

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#405]
### Type of feature

🍕 Feature

### Current behavior

The hot repositories are hard coded and need to be dynamic. 

![Screen Shot 2022-11-29 at 3 10 57 PM](https://user-images.githubusercontent.com/5713670/204960169-298102c6-fccd-400e-8f83-94e246d354e3.png)

### Suggested solution

Implement a solution for finding the repos with the most votes each week. Votes will need to be filtered by week and counted using this service. 

If there are no votes the service should fall back to using the submissions as the default. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
The screenshot is not working :D

**Comment by bdougie** [comment]
will work on this on #476
