### ISSUE TITLE
Bug: Discord is no longer receiving messages from repo submission. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#409]
### Describe the bug

This is the original implementation - https://github.com/open-sauced/hot/pull/212

There was an update to Discord that broke the auth to send messages. 

### Steps to reproduce

Navigate to hot.opensauced.pizza and submit a repo. 

![Screen Shot 2022-11-29 at 4 25 12 PM](https://user-images.githubusercontent.com/5713670/204677823-f7a00978-b692-42e6-9a91-462c432d5f75.png)

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
I think I commented the discord webhook url on #310 because of this comment -> https://github.com/open-sauced/hot/pull/310#discussion_r947784153
https://github.com/open-sauced/hot/blob/b3b0e128ab9979ca03497d68518ca3136a6caa16/src/lib/discord.ts#L4-L9

**Comment by RozzaysRed** [comment]
.take

**Comment by 0-vortex** [comment]
Yes, unfortunately it is not sustainable to send webhooks from the client react application and all of that has been moved to the backend. I will follow up with a new issue on this to remove the dead code, sorry for the inconvenience 💯
