### ISSUE TITLE
Feature: Set up filter logic

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#41]
### Type of feature

Feature

### Current behavior

The filters on the page exist as empty links. These are meant filters based on their relevantly named label. 

<img width="532" alt="Screen Shot 2021-12-26 at 8 48 25 AM" src="https://user-images.githubusercontent.com/5713670/147410367-798abda6-bc96-4378-8a9f-0cabc959e9e6.png">

### Desired solution
Some sort of Filter State logic should get added, similar to the [LayoutToggle](https://github.com/open-sauced/hot/blob/226768ffbb8220e6888b8ed9f0a7044bba1e55cd/src/components/LayoutToggle.jsx#L3) (state). 

Label | How it should work 
-|-
Popular | Default API filter (by [most starred by open sauced](https://github.com/open-sauced/hot/blob/226768ffbb8220e6888b8ed9f0a7044bba1e55cd/src/data/hot.json#L7) users)
Upvoted | Not yet implemented #12 
Discussed | Filter by [issue count](https://github.com/open-sauced/hot/blob/226768ffbb8220e6888b8ed9f0a7044bba1e55cd/src/data/hot.json#L6)
Recent | Filter by lowest [avg_recency_score](https://github.com/open-sauced/hot/blob/226768ffbb8220e6888b8ed9f0a7044bba1e55cd/src/data/hot.json#L8)

### Additional context

This feature should apply a filter and re-order how the repos are listed on the page. This is a common feature and there are a number of examples out there. 

https://medium.com/suyeonme/react-how-to-implement-an-infinite-scroll-749003e9896a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blackgirlbytes** [comment]
.take

**Comment by blackgirlbytes** [comment]
No clue how to do this, but I've been watching the open issues for this..and hoping I can dive in :)

**Comment by bdougie** [comment]
Cool, let me know if you have any questions. I think the filter state can live in the SecondaryNav component and the reset can be implemented just like a react component. 

A bonus would be including [routing](https://docs.astro.build/es/core-concepts/routing/) to the filtering.

**Comment by hokagedemehin** [comment]
This is a tricky one but I think I can give it a shot if that is ok... 😎

**Comment by hokagedemehin** [comment]
.take

**Comment by blackgirlbytes** [comment]
lol, uh, thanks for taking this on @hokagedemehin . I'll take a different issue then.
