### ISSUE TITLE
e2e testing: repo submissions

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#411]
Implement Cypress integration testing that supports the repo submission. 

note: https://github.com/open-sauced/hot/pull/408 related

Accessibility should also be tested.

**Comment by TAKANOME-DEV** [comment]
.take

**Comment by TAKANOME-DEV** [comment]
@bdougie it seems like there is an issue with the github action :thinking: 

![issue1](https://user-images.githubusercontent.com/79809121/205462429-5571904d-49ff-4643-93e8-5a0aaf254277.png)
