### ISSUE TITLE
e2e testing: filtering repos

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#412]
Filtering repos should test that the results are updated. Open to suggestions and questions. 

<img width="1416" alt="Screen Shot 2022-11-29 at 9 34 46 PM" src="https://user-images.githubusercontent.com/5713670/204715924-c90498d7-6afa-42c1-ae67-60abcbdf9276.png">

Accessibility should also be tested.

**Comment by nickytonline** [comment]
I'd like to .take this

**Comment by nickytonline** [comment]
Can I `.take` this one?
