### ISSUE TITLE
e2e testing: paginations of repos

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#413]
Pagination context is the "load more" button. The button should appear when there are more repos to show.

<img width="235" alt="Screen Shot 2022-11-29 at 9 35 47 PM" src="https://user-images.githubusercontent.com/5713670/204716063-12a31ea2-75c7-4b30-bcac-63df33f11cc2.png">

Accessibility should also be tested.

**Comment by ghorus** [comment]
hi, has that feature been added yet? 

also, on a side note: 
 it seems the page can also benefit from a view selector where they cuold change the amount of columns to view projects so they don't have to scroll all the way down. And also there seems to be a flash of unstyled content that could be an easy fix as well.

sorry if i'm mistaken!

**Comment by nickytonline** [comment]
Hi @ghorus, thanks for chiming in. This hasn't been worked on yet. It's an old issue that the team will reevaluate at some point.
