### ISSUE TITLE
Feature: submit new repo with shortcut

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#415]
### Type of feature

🍕 Feature

### Current behavior

If you want to submit a new repository for suggestions, you can't use shortcuts like cmd+enter/enter or escape to close the popup window

### Suggested solution

Here is an example
https://github.com/open-sauced/hot/blob/ecebb1ef0e85d46fb2fa67424081ae9250ff991e/src/components/Hero.tsx#L17-L44

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
I saw that we have `headlessui/react`. I think it can handle that (accessibility included) and even for the `hero search` we can use [headlessui combobox](https://headlessui.com/react/combobox)

**Comment by NsdHSO** [comment]
For the moment in this component we don't use [headlessui combobox](https://headlessui.com/react/combobox) we use native input. I think if you want can you open a new issue, to see what the other colleagues say

**Comment by 0-vortex** [comment]
> I saw that we have `headlessui/react`. I think it can handle that (accessibility included) and even for the `hero search` we can use [headlessui combobox](https://headlessui.com/react/combobox)

We do, we can also leverage [radix components](https://www.radix-ui.com/docs/primitives/overview/introduction)


> For the moment in this component we don't use [headlessui combobox](https://headlessui.com/react/combobox) we use native input. I think if you want can you open a new issue, to see what the other colleagues say

It does not make sense to complicate the current solution with keyboard accessibility when the baseline itself is not very accessible. I would agree the keyboard shortcut would be nice to have on top of an already accessible dropdown menu that displays some more information while typing and potential errors inline. 

IMHO the UI components we have installed already could take care of a11y and enable this issue to be done, but it should at least mention improving the baseline! 🍕

**Comment by TAKANOME-DEV** [comment]
> We do, we can also leverage [radix components](https://www.radix-ui.com/docs/primitives/overview/introduction)
>
Oh, didn't know about [radix](https://www.radix-ui.com/docs/primitives/overview/introduction), it looks great :100: 

> IMHO the UI components we have installed already could take care of a11y and enable this issue to be done, but it should at least mention improving the baseline! pizza
>
Yeah using [radix react dropdown](https://www.npmjs.com/package/@radix-ui/react-dropdown-menu) will fix this issue :pizza:

**Comment by bdougie** [comment]
> How can I contribute to this?

Do you have any suggestions or approach based on the existing conversation?
