### ISSUE TITLE
Bug: Footer not stay at the bottom 

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#417]
### Describe the bug

![Screenshot 2022-11-30 at 10 18 07](https://user-images.githubusercontent.com/37635083/204744085-e44de284-3127-4b8a-86e2-338dc42c6794.png)

### Steps to reproduce

1. Open in the hot app

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by me-manikanta** [comment]
I can `.take` this issue 😁

**Comment by a0m0rajab** [comment]
Seems like the issue has been solved, I could not reproduce it.

**Comment by NsdHSO** [comment]
Can you please provide your steps? Because I opened in hot, and reproduced this issue

**Comment by Themesses** [comment]
on mobile the socials socials seem cutoff in the footer as well 

![IMG_3421](https://user-images.githubusercontent.com/43274289/210612504-f56ecd8c-6915-47c3-85e7-7bc890c1e340.PNG)

**Comment by a0m0rajab** [comment]
I opened it from the browser directly: https://hot.opensauced.pizza/ 
I should mention that I had an issue with cache before which used to load an old version but solved by using: ```CTRL+SHIFT+R``` 
command

**Comment by ganeshrevadi** [comment]
Still an issue?

**Comment by NsdHSO** [comment]
Yes, the footer still has this issue.

**Comment by ganeshrevadi** [comment]
Okay ! Here's what I understood from the issue and web page .
The footer needs to persist even if the page is scrolled. Am I right ?
and any suggestions?

**Comment by NsdHSO** [comment]
Yes, this is what we need.

**Comment by VinceCYLiao** [comment]
@NsdHSO Is the footer in the video acting as you want ? If yes, please let me know and I'll create a pull request. Thanks!
https://github.com/open-sauced/hot/assets/46563912/c01f210a-b97c-433c-bbbe-a194ddbf16f6

**Comment by NsdHSO** [comment]
@VinceCYLiao sorry I can't open this video

**Comment by VinceCYLiao** [comment]
@NsdHSO Sorry I should convert the video into gif. Please check, thanks.
![footer](https://github.com/open-sauced/hot/assets/46563912/acaf1b89-7e3a-4106-807d-6cc5e89857c6)

**Comment by westernal** [comment]
Correct me if I'm wrong but I think its because the list of repositories renders after few seconds (waiting for server's data) and there is no loading component to render in the time the component is fetching the data from server so I added the loader and made a PR if it helps.

**Comment by NsdHSO** [comment]
@westernal Yes, this is what we want, Tnx for your PR, but can you please check this little [doc](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)
