### ISSUE TITLE
Feature:  Search pop-up don't close If I shot Escape 

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#418]
### Type of feature

🍕 Feature

### Current behavior

![image](https://user-images.githubusercontent.com/37635083/204744557-ce4f05ba-7a05-450a-9ea3-acf7bd733620.png)

### Suggested solution

I was expecting the pop-up to close when I pressed escape

#415

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
As commented on https://github.com/open-sauced/hot/issues/415#issuecomment-1331821017 using [headlessui combobox](https://headlessui.com/react/combobox) will fix that

**Comment by RozzaysRed** [comment]
.take
