### ISSUE TITLE
Unused code files (add dev-time detection?)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [open-sauced/hot#432]
When working on #431 I noticed the `lib/gitHubAPI.ts` file is wholly unused. It was added as part of #401 but that PR's discussion resolved not to use it.

I then ran [ts-prune](https://github.com/nadeesha/ts-prune) and found a few more files that aren't referenced anywhere. https://github.com/open-sauced/hot/commit/2f5da99d28010f941ea77baf32a8172858b49225

Would you like me to send a PR for this? I'd also recommend enabling it in CI.

**Comment by bdougie** [comment]
Seems like a nice thing to add to our CI, for sure. It was added during some other work that we did not move forward with. I'd love to see it added. 

cc @0-vortex our devexperiecne & tooling expert.
