### ISSUE TITLE
Bug: Footer on mobile - social icons cut off; remove height from footer

### ISSUE THREAD

**Issue by Themesses** [open-sauced/hot#435]
### Describe the bug

In mobile view, footer h-24 cuts off the socials and rest of the content at any resolution below 1023px wide. Should remove the height from the footer element. 
![IMG_3421](https://user-images.githubusercontent.com/43274289/210626764-11025114-533f-4479-a249-6ab4ded96720.PNG)

### Steps to reproduce

1. go to main page
2. open dev tools
3. scroll down to the footer
4. screen width < 1023px
5. socials cut off 

### Affected services

hot.opensauced.pizza

### Platforms

Mobile

### Browsers

Chrome, Safari

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Themesses** [comment]
happy to tackle it or delete it if it's already being addressed

**Comment by 0-vortex** [comment]
> happy to tackle it or delete it if it's already being addressed

Feel free to [dot take](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues) this, can assign you if the workflow does not work!

**Comment by Themesses** [comment]
Awesome, thanks!

**Comment by Themesses** [comment]
.take

**Comment by Themesses** [comment]
> > happy to tackle it or delete it if it's already being addressed
> 
> Feel free to [dot take](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues) this, can assign you if the workflow does not work!

Didn't seem to work. if you can assign it I would appreciate it.
