### ISSUE TITLE
Feature: responsiveness in HotRepoCard

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#437]
### Type of feature

🍕 Feature

### Current behavior

In phone mode it looks very bad, we want to improve our user experience, we are an organization that wants to give the user a good feeling.

### Suggested solution
<img width="1607" alt="Screenshot 2023-01-05 at 11 15 36 AM" src="https://user-images.githubusercontent.com/37635083/210790800-9445b19e-f61e-469d-bca6-27bd29f494fe.png">

Create a wrapper
[lines](https://github.com/open-sauced/hot/blob/c44f5c114c3a9860a75d572a87af313085853b7b/src/components/HotRepoCard.tsx#L69&L114)
In small breakpoint you should put ` display flex ` on the wrapper.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
@NsdHSO the image in the *Suggested Solution* section seems to be broken

**Comment by NsdHSO** [comment]
@TAKANOME-DEV Tnx.

**Comment by RozzaysRed** [comment]
.take
