### ISSUE TITLE
Bug: Mobile view - when signed in, 'my votes' background wraps unexpectedly

### ISSUE THREAD

**Issue by Themesses** [open-sauced/hot#438]
### Describe the bug

When signed in, 'my votes' is added to the nav below the hero. When clicked, the text-wrap of the menu item is causing the background color to wrap unexpectedly as well. 
![IMG_8FFC0F13F480-1](https://user-images.githubusercontent.com/43274289/210813198-56e94261-62a4-4c68-a7a9-51495c9aa514.jpeg)

### Steps to reproduce

1. Main page on mobile ( width < 466px)
2. Sign in with Github
3. Menu below hero
4. Click on 'my votes'

### Affected services

hot.opensauced.pizza

### Platforms

Mobile

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Nice catch @Themesses 👏
Can assign you if you want to take it 🍕

**Comment by Themesses** [comment]
.take

**Comment by Themesses** [comment]
thanks @TAKANOME-DEV ☺️

**Comment by 0-vortex** [comment]
My suggestion would be to wrap the links on 2 rows, but doing so might require some flex classes changed, what do you think?

The menu could definitely use some love, feel free to open improvement idea issues if you have thoughts! 🍕 ❤️

**Comment by Themesses** [comment]
There is definitely a point where it should wrap. I'll play around and follow up.
