### ISSUE TITLE
Bug: Should not show load more button if there is no more data

### ISSUE THREAD

**Issue by imvedanshmehra** [open-sauced/hot#446]
### Describe the bug

"Load More" button should disappear if there is no more data 

https://user-images.githubusercontent.com/44801561/216786466-2a8e7ecc-fbb4-47ad-b8c7-ef224fd273aa.mp4

### Steps to reproduce

1. Go to the homepage
2. Navigate to any of the tabs from "Recent", "Upvoted", "Discussed", "Popular"
3. Scroll down to the end of the page
4. Click on **Load More** button, it won't load any data

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Good catch! 👍

**Comment by imvedanshmehra** [comment]
@0-vortex can you please assign this to me? I'll look into it.

**Comment by TarekArar99** [comment]
@0-vortex can you assign it to me ?

**Comment by bdougie** [comment]
@TarekArar99 do you have a different approach?


Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by deepakrudrapaul** [comment]
.take
