### ISSUE TITLE
Bug: no padding or margin bottom at the footer

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/hot#450]
### Describe the bug

currently there is no padding bottom at the end of the footer on small & medium devices

### Steps to reproduce

1. go to [https://hot.opensauced.pizza/](url)
2. scroll down

### Affected services

hot.opensauced.pizza

### Platforms

Mobile, Tablet

### Browsers

Chrome

### Additional context

i could fix this 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Can you add a screenshot?

**Comment by dev-phantom** [comment]
Sure👍
![Screenshot_20230226-013259](https://user-images.githubusercontent.com/72051159/221386000-35606c2f-4bae-4928-971e-cdc0b9987677.png)

**Comment by TAKANOME-DEV** [comment]
Sure, go ahead.
