### ISSUE TITLE
Bug: recent and my vote tabs are squashed

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/hot#451]
### Describe the bug

After signing in the recent tab and the my vote tabs are looking disordered on small screen sizes

Here's a screenshot:
![Screenshot_20230226-011839](https://user-images.githubusercontent.com/72051159/221385736-44637f5f-4c72-4847-b66d-4b6333dad3b3.png)

### Steps to reproduce

1. Go to [Hot open source ](https://hot.opensauced.pizza/) 
2. Click on sign In
3. Check recent and my vote

### Affected services

hot.opensauced.pizza

### Platforms

Mobile

### Browsers

Chrome

### Additional context

I can work on this 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by rajat4984** [comment]
.take

**Comment by TAKANOME-DEV** [comment]
Hum, this should have been fixed by https://github.com/open-sauced/hot/pull/440 :thinking:

**Comment by dev-phantom** [comment]
> Hum, this should have been fixed by https://github.com/open-sauced/hot/pull/440 :thinking: 

Yea seen it 
I'll look into this and fix it

**Comment by dev-phantom** [comment]
@TAKANOME-DEV please assign me to this

**Comment by dev-phantom** [comment]
@TAKANOME-DEV and @bdougie i thought one way to resolve this is to add `w-full`

but i also realized that in the styles were also not updated after deployment 
here's a screenshot:
![image](https://user-images.githubusercontent.com/72051159/221948328-2687229b-1459-4bb4-8eee-a7cd52ae570f.png)

but it's updated in the repo 
![image](https://user-images.githubusercontent.com/72051159/221951660-b37e4f6e-f896-46a7-9507-98bedd0f22ce.png)

so i guess this is a deployment issue

**Comment by dev-phantom** [comment]
here is the release for #440 

![image](https://user-images.githubusercontent.com/72051159/221954396-52cc0f21-2db6-4e32-9b95-c444932fae09.png)

but here is the latest release 
![image](https://user-images.githubusercontent.com/72051159/221955090-8b60180c-b02c-4041-ba33-fb1ae4b040f6.png)

**Comment by TAKANOME-DEV** [comment]
@dev-phantom thanks for taking the time to investigate this issue.
As mentioned earlier this was resolved in pr 440 but I think it's on the beta branch, not yet merged into main.

**Comment by dev-phantom** [comment]
> @dev-phantom thanks for taking the time to investigate this issue.
> As mentioned earlier this was resolved in pr 440 but I think it's on the beta branch, not yet merged into main.
> 
> Visit [beta.hot.opensauced.pizza](https://beta.hot.opensauced.pizza) and try it out

Do you think I should still leave this issue open or close it

**Comment by TAKANOME-DEV** [comment]
It can be closed since it was already resolved.
Thanks again for taking the time to fill this issue :+1:
