### ISSUE TITLE
Bug: Copyright year should be updated

### ISSUE THREAD

**Issue by tmsagarofficial** [open-sauced/hot#455]
### Describe the bug

In the footer of this site, we can see that the year is 2022
<img width="328" alt="image" src="https://user-images.githubusercontent.com/110724849/226168452-6379d6dd-c489-4232-968c-7cc0f33ba57a.png">
which needs to be updated 

and also it should be automated to change automatically when the year changes

### Steps to reproduce

1. Go to https://hot.opensauced.pizza/
2. Scroll till the end 
3. Notice that the year beside the copyright symbol needs to be updated

### Affected services

hot.opensauced.pizza

### Platforms

Desktop, Mobile, Tablet, TV

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Pratham-19** [comment]
.take

**Comment by tmsagarofficial** [comment]
Thanks for letting me contribute 🚀
