### ISSUE TITLE
The icons at the bottom not visible in mobile mode

### ISSUE THREAD

**Issue by parmishh** [open-sauced/hot#459]
### Describe the bug

The icons at the bottom not visible in mobile mode
@bdougie I want to work on this it can be assigned to me.

<img width="538" alt="cut" src="https://user-images.githubusercontent.com/91942072/227721459-e90e6729-9740-4c8d-a2a8-4eb3b01cde20.PNG">

![Screenshot_20230325-191826_Chrome](https://user-images.githubusercontent.com/91942072/227721694-2d1f8183-6000-4746-b7d1-2c496598bcf3.jpg)

### Steps to reproduce

Already present on site on mobile mode

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by parmishh** [comment]
.take

**Comment by TAKANOME-DEV** [comment]
Hey @parmishh, thanks for opening this issue.
This was already tackled in https://github.com/open-sauced/hot/pull/436. It's in the beta branch, visit [beta.opensauced.pizza](https://beta.hot.opensauced.pizza/) 

We gonna close this issue for now, let us know if it's still present and we will re-open it :pizza:
