### ISSUE TITLE
Feature: functionality to enable filtering of repositories according to programming languages they comprise of

### ISSUE THREAD

**Issue by solaries** [open-sauced/hot#464]
### Type of feature

🍕 Feature

### Current behavior

When the page loads you see repositories and a filter field for filtering according to repositories titles.  The information displayed regarding the repositories don't show the programming language used in them, neither is there a way of filtering them according to one or more programming languages.

### Suggested solution

In addition to the "filter according to title "  field, there should be a series of checkboxes labeled according to the programming languages used in the repositories being loaded. When none of them are checked, all the repositories will be as is. As a language is checked, the repository listing is filtered according to checked programming languages.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bethasiva** [comment]
Would you assign me to this issue? I want to work on this feature.

**Comment by Sadaf-A** [comment]
Hey, I wanted to to work on this issue could some please assign?

**Comment by AkshataABhat** [comment]
.take
