### ISSUE TITLE
Bug: Icons in the input field of the hero section could be aligned

### ISSUE THREAD

**Issue by Sadeedpv** [open-sauced/hot#473]
### Describe the bug

Icons in the input field of the hero section in the [page](https://hot.opensauced.pizza/) could be aligned with a simple flex;

### Steps to reproduce

1. Go to https://hot.opensauced.pizza/ hero section of the page to see the input field.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Sadeedpv** [comment]
Please assign the issue to me

**Comment by Sadeedpv** [comment]
.take

**Comment by PrgrmrHarshShukla** [comment]
Hey @Sadeedpv , @bdougie ,
I would love to work on the issue.
Am I allowed to do so, as I can see it is assigned to someone?

**Comment by bdougie** [comment]
> Hey @Sadeedpv , @bdougie ,
> 
> I would love to work on the issue.
> 
> Am I allowed to do so, as I can see it is assigned to @Sadeedpv ?

There is already a or, which I just merged. Feel free to take a look at other issues.

**Comment by PrgrmrHarshShukla** [comment]
> > Hey @Sadeedpv , @bdougie ,
> > I would love to work on the issue.
> > Am I allowed to do so, as I can see it is assigned to @Sadeedpv ?
> 
> There is already a or, which I just merged. Feel free to take a look at other issues.

Hey @bdougie ,
Thanks.
Will look into other issues.
