### ISSUE TITLE
Bug: Auth on beta.hot.opensauced.pizza is broken

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/hot#477]
### Describe the bug

https://github.com/open-sauced/hot/assets/79809121/2e559966-c960-439e-afec-8fc3b9dee6f7

### Steps to reproduce

1. Visit [beta.hot.opensauced.pizza](https://beta.hot.opensauced.pizza/)
2. Click on the signing button

### Browsers

Chrome, Firefox

### Additional context (Is this in dev or production?)

The variables in the `.env` file must be outdated I think :thinking:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
https://github.com/open-sauced/landing-page/issues/135#issuecomment-1662665880 
this could also work here so there will be only one supabase authentication set up (which will be in the insights repo)
