### ISSUE TITLE
fix: repo not found [open-sauced/insights]

### ISSUE THREAD

**Issue by maheshrjl** [open-sauced/hot#484]
Please take a look why this  open-sauced/insights not founded

![image](https://github.com/open-sauced/hot/assets/62394512/a5e9fa77-56ca-4e5c-bf3f-e5a5fc19aa93)

**Comment by bdougie** [comment]
That is because the repo being renamed to open-sauced/app.

Currently it is hard coded in the HotRepositories. If anyone wants to fix, it would be a quick contribution.

**Comment by maheshrjl** [comment]
@bdougie I managed find the repo reference & update it. Pushed to https://github.com/open-sauced/hot/pull/485
