### ISSUE TITLE
Feature: Integrate million.js

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/hot#486]
### Type of feature

🍕 Feature

### Current behavior

Continued conversation from https://github.com/open-sauced/app/pull/1608 for @ayusham001

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by ayusham001** [comment]
Hii @brandonroberts 
Please review my PR at https://github.com/open-sauced/hot/pull/487
