### ISSUE TITLE
Adding hover effect for the buttons

### ISSUE THREAD

**Issue by Sadeedpv** [open-sauced/hot#491]
### Type of feature

🎨 Style

### Current behavior

Currently, the buttons do not have any hover effects and is not interactive. Hover effects can make the website more effective and interactive.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Sadeedpv** [comment]
.take

**Comment by bdougie** [comment]
Thanks for opening this up @Sadeedpv. Not sure of the value this provides. In the future please provide more context before proceeding with a PR.

**Comment by Sadeedpv** [comment]
@bdougie As of now, buttons do not have any hover effects. Adding hover effects can bring more interactability to the website.

**Comment by bdougie** [comment]
I don't think there is enough evidence that this is needed.
