### ISSUE TITLE
fix: repo not found [ThePrimeagen/undefined]

### ISSUE THREAD

**Issue by sp6370** [open-sauced/hot#495]
Please take a look why this  ThePrimeagen/undefined not founded

**Comment by jpmcb** [comment]
Hi @sp6370 - looks like it is showing up:

![Screenshot 2023-10-18 at 8 49 51 AM](https://github.com/open-sauced/hot/assets/23109390/96380ae5-19e6-41f0-afc3-495d51840eb4)

what are you seeing? Is it missing for you? Any and all details will help us debug this. Thanks much!

**Comment by sp6370** [comment]
Weird! I am seeing it as well now. I will close the issue. Thanks for responding promptly.

**Comment by jpmcb** [comment]
Might have just caught it before our service indexed it!
