### ISSUE TITLE
Feature: cut over to v2 API

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/hot#508]
### Type of feature

🍕 Feature

### Current behavior

Related: https://github.com/open-sauced/api/issues/478

### Suggested solution

The v1 API is being deprecated: we should cut over to the v2 API and tee up changes ready for when the v1 API goes down

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Sure thing! Should be pretty simple for the hot repo since there's not much that's changing besides `v1` to `v2`: here's the new API - https://alpha.api.opensauced.pizza/

Ping me if you have questions!

**Comment by jpmcb** [comment]
Hey @takanome-dev - We're getting really close to doing the v2 cutover: any progress here?

I may reassign this to me if you haven't started working on it yet since this was originally intended to be core team work and we're moving pretty fast on making this v1 --> v2 transition happen.

**Comment by takanome-dev** [comment]
Hey @jpmcb, I haven't started it yet. I was planning to tackle it over the weekend, as I thought there was still some time before v2 is ready. However, if it's time-sensitive for the core team, please go ahead and reassign. Apologies for any inconvenience, and thanks for the understanding!

**Comment by jpmcb** [comment]
No worries! I'll assign myself: we ended up moving much faster on this than I anticipated. Thanks for grabbing this tho!

**Comment by jpmcb** [comment]
Re-opening since we'll also want to track this going into production next week.

**Comment by jpmcb** [comment]
Re-opening since we'll also want to track this going into production next week.

**Comment by jpmcb** [comment]
Closed by: https://github.com/open-sauced/hot/pull/510
