### ISSUE TITLE
API Key is not working

### ISSUE THREAD

**Issue by jimbobbennett** [open-sauced/hot#512]
Not sure if this is the right repo for this - I generated an API token following the [docs](https://docs.opensauced.pizza/contributing/set-up-authentication/), and I'm still getting unauthorized when I call the API.

<img width="1202" alt="image" src="https://github.com/open-sauced/hot/assets/1710385/2db9dce9-5546-41f7-80c5-17c23453e806">

**Comment by nickytonline** [comment]
Hmmm, my coworker @brandonroberts did a quicj the and the token generated works with https://api.opensauced.pizza/#/Authentication%20service/checkAuthSession

**Comment by jimbobbennett** [comment]
Well found the issue...

It seems if I generate the token with Safari, it's not valid and I get a 401. If I use Edge it works.

Looks like Safari is truncating the API Key in the console output. There's a `.<something>` on the end of the key that Safari is losing.

Maybe something to add to the docs? I'll close this issue for now, thanks @nickytonline and @jpmcb

**Comment by nickytonline** [comment]
I'll go ahead and create an issue for that. Thanks @jimbobbennett!
