### ISSUE TITLE
Bug: Safari is truncating the API Key in the console output

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/hot#513]
When generating the token in Safari API Key gets truncated in the console output. We should add this to the docs around API key generation.

For more context, see @jimbobbennett's comment in https://github.com/open-sauced/hot/issues/512#issuecomment-1930919711_

**Comment by OmkarPh** [comment]
Hi, instead of just printing the token to console, why not copy it directly to clipboard ?

**Comment by takanome-dev** [comment]
> Hi, instead of just printing the token to console, why not copy it directly to clipboard ? I can take this up

Sounds like THE solution, please go ahead 👍
