### ISSUE TITLE
Bug:  PostList component overlapping in mobile viewport

### ISSUE THREAD

**Issue by kelvinsekx** [open-sauced/hot#53]
### Describe the bug

When using the toggle to change Post from Grid to List, the list form overlaps the mobile viewport. Causing poor UX

Present behavior
![Screenshot_20211231-081140~2](https://user-images.githubusercontent.com/51183064/147809277-dbdc21cd-eedb-4d9a-b4b5-461ee7a46cc3.jpg)

Expected behavior
![Screenshot_20211231-081112](https://user-images.githubusercontent.com/51183064/147809287-1ddd903c-2306-4a92-87c7-59b16e06345e.jpg)

### Steps to reproduce

1. Visit https://hot.opensauced.pizza/ in any mobile browser, preferable chrome
2. Click the LayoutToggle to allow from Grid to PostList
3. Confirm the behavior

### Affected services

opensauced.pizza

### Platforms

Mobile

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hokagedemehin** [comment]
.take
