### ISSUE TITLE
Feature: Replace the discussion svg with the github issue one. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#54]
### Type of feature

Fix

### Current behavior

This icon is for comments, but should be for issues
![Screen Shot 2021-12-31 at 2 51 40 PM](https://user-images.githubusercontent.com/5713670/147840636-a2f51c34-ac08-4a8b-8065-b8adc3955f54.png)

### Desired solution

Should be the circle with a dot. 
![Screen Shot 2021-12-31 at 2 52 57 PM](https://user-images.githubusercontent.com/5713670/147840643-3a2d0181-c745-486c-badf-5d289009ea97.png)

https://fontawesome.com/v5.15/icons/dot-circle?style=regular

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by whoiskekeanyway** [comment]
I am trying to fix the issue, but I have never worked with docker. Could you tell me which file this particular line of code is inside?

**Comment by kelvinsekx** [comment]
You don't necessarily need to be vaxed with docker. 
It isn't a barrier.

**Comment by whoiskekeanyway** [comment]
> You don't necessarily need to be vaxed with docker. It isn't a barrier.

Thank you. I figured it out. Thanks to stackblitz
