### ISSUE TITLE
Bug: Unusual size of SVG issues icon

### ISSUE THREAD

**Issue by kelvinsekx** [open-sauced/hot#58]
### Describe the bug

1. Go to https://hot.opensauced.pizza/
2. Switch post display toggle to list
3. See the unusual size
![Screenshot_20220103-154144_1~2](https://user-images.githubusercontent.com/51183064/147945438-8e95d91c-1197-4de9-8105-57f203a50553.jpg)

### Steps to reproduce

1. Go to https://hot.opensauced.pizza/
2. Switch and see error

### Affected services

opensauced.pizza

### Platforms

Desktop, Mobile

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blackgirlbytes** [comment]
.take

**Comment by mtfoley** [comment]
Looks OK to me on Chrome for Windows (they're all larger).
![image](https://user-images.githubusercontent.com/3792749/147952620-7a2bab59-f454-43a9-b987-7629efd73f4c.png)

Don't know if there's a service worker at play on this site, but occasionally we'd see a need for clearing caches on opensauced.pizza when verifying visual issues.

They looked this way on #56 deploy preview as well.

**Comment by blackgirlbytes** [comment]
see here 

<img width="1117" alt="Screen Shot 2022-01-03 at 11 19 16 AM" src="https://user-images.githubusercontent.com/22990146/147954156-bb916cb2-03dc-4593-95f3-18855498139f.png">
<img width="1147" alt="Screen Shot 2022-01-03 at 11 19 27 AM" src="https://user-images.githubusercontent.com/22990146/147954164-91a0a7ac-ca45-4fd6-aec9-847a4ea1a522.png">

**Comment by hokagedemehin** [comment]
@blackgirlbytes you have good eyes to have spotted that out

You are doing well ☺️
