### ISSUE TITLE
Bug: variable container width in post list view mode

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#61]
### Describe the bug

The icons in the list view mode are spread out based on how long the repository description is, it should have full width and min/max height sensible defaults

<img width="1735" alt="Screenshot 2022-01-04 at 12 00 55" src="https://user-images.githubusercontent.com/237133/148042753-aea81c93-bc4d-4358-959d-cc51b2c53a04.png">

### Steps to reproduce

1. go to https://hot.opensauced.pizza
2. toggle the list view mode

### Affected services

opensauced.pizza

### Platforms

Desktop, Mobile, Tablet, TV, VR

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hokagedemehin** [comment]
Hi @0-vortex 

I have some questions on this issue, would appreciate if you can clarify them

- should the width of the card be reduced based on the content of the card or it should still remain the way it is as the full width of the page
- should we adjust only the action buttons so that they are equally spaced out no matter the content of the description in the card, so as for t to look consistent across all cards in the page

**Comment by 0-vortex** [comment]
> * should the width of the card be reduced based on the content of the card or it should still remain the way it is as the full width of the page

In my opinion the card should stay the same and the div with `text-lightGrey text-xs sm:text-base` should go 100% width to match the card.

> * should we adjust only the action buttons so that they are equally spaced out no matter the content of the description in the card, so as for t to look consistent across all cards in the page

I believe so, however, I would not be able to tell what the best layout here would be, aligned left with min-width or covering the full length of the container, would experiment with that locally or poke @bdougie for creative direction 🍕

**Comment by hokagedemehin** [comment]
Alright then, will experiment on my side and make PR when I have something to present

**Comment by mtfoley** [comment]
> Alright then, will experiment on my side and make PR when I have something to present

Might be good to comment with some screenshots of your experiments 👀

**Comment by hokagedemehin** [comment]
> > Alright then, will experiment on my side and make PR when I have something to present
> 
> Might be good to comment with some screenshots of your experiments 👀

A better suggestion

**Comment by bdougie** [comment]
My gut says.

```css
justify-content: flext-start # justify-start in tailwind
margin-right: 1rem # mr-4 or similar in tailwind
```

**Comment by hokagedemehin** [comment]
> My gut says.
> 
> ```css
> justify-content: flext-start # justify-start in tailwind
> margin-right: 1rem # mr-4 or similar in tailwind
> ```

This will actually work, but for me instead of using `mr-4` I would use `space-x-2`

This will actually still space each of the item without adding an extra space at the end of the last item

**Comment by hokagedemehin** [comment]
Hello @0-vortex 

What do you think??

![Screenshot 2022-01-06 114915](https://user-images.githubusercontent.com/16826624/148371532-99d75c00-7df3-4da3-8281-3bad175885dd.png)

**Comment by 0-vortex** [comment]
> Hello @0-vortex
> 
> What do you think??
> 
> ![Screenshot 2022-01-06 114915](https://user-images.githubusercontent.com/16826624/148371532-99d75c00-7df3-4da3-8281-3bad175885dd.png)

That's looking much better, one improvement I would add here is to make the 3 centainers have 1.5x min-width, like 1st box has 5 upvotes but 11ty has 441 issues and coding-interview has 41, giving them a min display for 4 letter box would make the 3rd column stars (10.9k vs 201.8k vs 337.7k) also be aligned.

Translating thousands into "k" units gives us a 5 character min-width we should use to have everything aligned, hopefully forever 🍕

**Comment by kelvinsekx** [comment]
Giving each of the containers a min-width will make it look cooler. And if possible increase the containers wrapper all together, I mean the width

**Comment by hokagedemehin** [comment]
@0-vortex @kelvinsekx 

👀

![Screenshot 2022-01-06 201148](https://user-images.githubusercontent.com/16826624/148438008-5aacb062-25fd-4988-b320-ea3c3a6dee9b.png)

**Comment by hokagedemehin** [comment]
.take
