### ISSUE TITLE
Testing the filter Navlinks

### ISSUE THREAD

**Issue by hokagedemehin** [open-sauced/hot#64]
### Describe the bug

1. On your laptop, open this project with your code editor, paste `gh pr checkout 57` in the terminal and run it, to have a copy of the changes reflecting on this pull request #57 
2. run `npm ci` then `npm start` to spin up a server and go to `localhost:3000` to start testing. If you click on any of the secondary nav links it should highlight that link alone with a yellow background

### Steps to reproduce

1. Click on any of the links (Popular | Upvoted | Discussed | Recent) to make sure it sorts the cards based on the criteria given on issue #41 
2. Popular and Upvoted Link should return the same result, while Discussed and Recent should return different order of the cards displayed
3. If you refresh the page, it should return back to default

#### Popular

![Screenshot 2022-01-02 215511](https://user-images.githubusercontent.com/16826624/148207705-ae370e70-e5d8-44f8-bddd-0b2f8d9ef0b4.png)

#### Upvoted
![Screenshot 2022-01-05 114726](https://user-images.githubusercontent.com/16826624/148207724-590c37a9-cfe6-45bd-9979-1803ef465117.png)

#### Discussed
![Screenshot 2022-01-02 215526](https://user-images.githubusercontent.com/16826624/148207759-19b32a0b-7f0d-4686-8075-58f45e915265.png)

#### Recent
![Screenshot 2022-01-02 222929](https://user-images.githubusercontent.com/16826624/148207834-7c56a98b-94d0-42f6-ae99-32c1af556e8d.png)

### Affected services

opensauced.pizza

### Platforms

Desktop, Mobile, Tablet

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Environment

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelvinsekx** [comment]
.take

**Comment by bdougie** [comment]
To be clear, to resolve this issue we need UI tests. The open sauced repo has some https://github.com/open-sauced/open-sauced/tree/main/src/tests

**Comment by bdougie** [comment]
https://github.com/open-sauced/hot/pull/82/files#r782156878

**Comment by bdougie** [comment]
Reopened, since tests were not added in #82. The approach can use the current static files as mock data and the filter can be tested as a unit test checking the order of the array.

https://github.com/open-sauced/hot/pull/82/files#r782156878

**Comment by bdougie** [comment]
Going to unassigned for now. This is probably dependent on the new API changes as well. FYI for anyone who is picking this up. https://github.com/0-vortex/api.opensauced.pizza

**Comment by bdougie** [comment]
This has been merged to beta. FYI, moving forward we want to follow this pattern. Also added this text to the README.

> For writing tests, the rule is move business or service logic to the lib folder and write unit tests. Logic that needs to be in a React component, then leverage tools like [Cypress](https://www.cypress.io/) or [Vitest mocking](https://vitest.dev/guide/mocking.html) to write tests.
