### ISSUE TITLE
Feature: Supabase Studio

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#68]
### Type of feature

Feature

### Current behavior

At the moment the only person that contributes to any database changes is @bdougie. While getting the project off the ground is fine, but this will be a limitation for future contributors as the site grows to be more complicated. 

### Desired solution

Connect the database to a local studio instance that folks run locally. This will require some sort RLS and user management which is still actively being worked on in #20 

If anyone has Supabase experience, feel free to comment here or in the discord. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
Can handle the docker and local development parts so will just `.take` this 🍕
