### ISSUE TITLE
Feature: Local developer env

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#70]
### Type of feature

Feature

### Current behavior

The PR #67 was merge and intentionally including public env vars.  https://github.com/open-sauced/hot/blob/main/src/lib/database.js#L4

The ideal approach will be adding that to the .env file since the DB does currently have security and everything accessible. 

### Desired solution

I think we should include context on how folks and generate their own local database using the mock data in https://github.com/open-sauced/hot/blob/main/src/data/hot.json file. 

1. Discover the steps to reproduce the DB per user (this require them to sign up for supabase)
2. Include the above steps in the README
3. Add new local dev supabaseurl and anon public key to an .env 

### Additional context

Open to suggestions, but this will be temporary until login is enabled

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
IMHO vote for a single `.env` packed with development value and having them overloaded during the release workflow with GitHub secrets 🍕

**Comment by bdougie** [comment]
Thinking on stream. We can you a private gist and then have contributors run `script/setup` or similar. https://gist.github.com/bdougie/f825111d344dd40ab79c7e8ef3b703d4

**Comment by 0-vortex** [comment]
.take
