### ISSUE TITLE
Feature: clean up tooling and remove astro (breaking)

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#80]
### Type of feature

Build

### Current behavior

We are unable to use [astro](https://astro.build) in several instances:
- code listing and formatting (due to missing eslint parser and language tools)
- cloud IDE providers (due to astro vs vite config mismatch)
- language completion and assistance in local IDEs (language tools need manual install and are not bundled with astro)
- production builds due to unresolved bugs (see #76)
- the technology is in perpetual alpha/beta since 2017
- [partial hydration](https://docs.astro.build/en/core-concepts/component-hydration/) the only feature we are missing, is not fully working and requires additional code

### Desired solution

1. strip `.astro` files into `.jsx`
1. apply vite bundler configuration from open-sauced so we can contribute without local install
1. replace head component with hydrated react-helmet or similar
1. switch to pre-rendered static content globally
1. apply service worker

### Additional context

doing this now will fix a lot of headaches for existing and future contributors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nulfrost** [comment]
+1, I can see the potential Astro has but as it stands right now it's more of a headache to work with

**Comment by bdougie** [comment]
Thanks for writing this up. Astro was a good experiment and fun to work with, but it has indeed shown to be limited to due how new it is. Working on this project, it is clear that adoption will be much higher than even the flagship https://opensauced.pizza and we will need to consider if should rewrite to a simple React SPA or another paved path would help us keep up the velocity at which we shipped this. 

My counterpoint would be if it is worth reaching out to the Astro team to begin triaging some of these limitations in their repo. Open Sauced's mantra is finding your next contribution and I think whether or not we stick with Astro we should at the very least report these limitations there in issues.

**Comment by nulfrost** [comment]
> Thanks for writing this up. Astro was a good experiment and fun to work with, but it has indeed shown to be limited to due how new it is. Working on this project, it is clear that adoption will be much higher than even the flagship https://opensauced.pizza and we will need to consider if should rewrite to a simple React SPA or another paved path would help us keep up the velocity at which we shipped this.
> 
> My counterpoint would be if it is worth reaching out to the Astro team to begin triaging some of these limitations in their repo. Open Sauced's mantra is finding your next contribution and I think whether or not we stick with Astro we should at the very least report these limitations there in issues.

Yup that sounds good, I'm sure someone else might encounter these problems too so submitting these would be very beneficial

**Comment by mtfoley** [comment]
> Thanks for writing this up. Astro was a good experiment and fun to work with, but it has indeed shown to be limited to due how new it is. Working on this project, it is clear that adoption will be much higher than even the flagship https://opensauced.pizza and we will need to consider if should rewrite to a simple React SPA or another paved path would help us keep up the velocity at which we shipped this. 
> 
> 
> 
> My counterpoint would be if it is worth reaching out to the Astro team to begin triaging some of these limitations in their repo. Open Sauced's mantra is finding your next contribution and I think whether or not we stick with Astro we should at the very least report these limitations there in issues.  


Based on reading up on handling environment variables server side, I think they have an RFC process now, rather than using issues (could be wrong).

**Comment by bdougie** [comment]
@0-vortex we should move forward with this. After a lot of thought and conversation, I think to react/vite is the correct path here. The [complexity planned for this project](https://github.com/orgs/open-sauced/projects/1) will ensure Astro is an albatross holding it down.

**Comment by 0-vortex** [comment]
> @0-vortex we should move forward with this. After a lot of thought and conversation, I think to react/vite is the correct path here. The [complexity planned for this project](https://github.com/orgs/open-sauced/projects/1) will ensure Astro is an albatross holding it down.

I'll pick this up this week, want to finish the drafts in hot and actions first. The open sauced boilerplate is very similar to open-sauced, just a matter of starting with less dependencies and written code.

**Comment by 0-vortex** [comment]
Time to `.take` this apart 👯
