### ISSUE TITLE
Feature: Make images clickable links

### ISSUE THREAD

**Issue by bdougie** [open-sauced/hot#83]
### Type of feature

Feature

### Current behavior

When view the PostGrid components, images are shown but not clickable. 

https://github.com/open-sauced/hot/blob/main/src/components/PostGrid.jsx#L41-L45

![Screen Shot 2022-01-11 at 4 06 41 PM](https://user-images.githubusercontent.com/5713670/149040911-9f67f70e-24a4-4c36-b930-320b590c1ace.png)

### Desired solution

Use the repolink to make them clickable. 

https://github.com/open-sauced/hot/blob/main/src/components/PostList.jsx#L16-L19

### Additional context

As a bonus, this should really be reuable from the PostWrap component.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hokagedemehin** [comment]
.take
