### ISSUE TITLE
Feature: document supabase

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/hot#93]
### Type of feature

📝 Documentation

### Current behavior

This issue is related to #68 . I think it would be helpful to have documentation of the supabase details for this repo.

### Suggested solution

I’d suggest:
- [ ] docs for database schema 
- [ ] Docs for queries used
- [ ] Sample data set

One nice-to-have could be https://github.com/zernonia/supabase-schema 👀

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment]
looks like a task for me :D

**Comment by 0-vortex** [comment]
Checking the schema visualiser out now, most of the Supabase CLI commands are documented in the README now!

**Comment by 0-vortex** [comment]
.take
