### ISSUE TITLE
Feature: Progressive Web Application feature included 

### ISSUE THREAD

**Issue by yhoungdev** [open-sauced/hot#95]
### Type of feature

🍕 Feature

### Suggested solution

I fixed that by adding a service worker and a manifest.json file 

###### Site now work offline ( from cached items )
![Screenshot from 2022-01-18 21-44-09](https://user-images.githubusercontent.com/54102389/150033334-47d7b3b8-ea8c-45ea-86a9-b9cc3e3a140b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdougie** [comment]
Mentioned in https://github.com/open-sauced/hot/issues/96 but also going to mention here. This project has 19 users to date and none have requested this feature. Some things to consider:

1. This will need documentation
2. This project is using Astro/Vite, will add a service worker? Astro's recommendation is less JavaScript, which makes me question the need for PWA features now while this project is only getting started.  

To be clear this will overall be a good addition, but we would need to know why now? Join us in the discord if you would like to chat.

**Comment by yhoungdev** [comment]
Yea would like to chat
