### ISSUE TITLE
Feature:  Loader should be added

### ISSUE THREAD

**Issue by yhoungdev** [open-sauced/hot#96]
### Type of feature

🍕 Feature

### Current behavior

A preloader should be added to the application 

### Suggested solution

Adding a loader will make it look good and improve user experience

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdougie** [comment]
@yhoungdev this issue and PR #94 leaves a lot to be desired. Can you add additional context to what a loader is and why it should be added? At the moment this project has 19 users and zero have requested this. 

Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to contribute as well.
